<?php

use Illuminate\Database\Seeder;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('municipios')->insert([
            ['id'=>'1 ','municipio'=>'EL ENCANTO','id_dpto'=>'1'],
            ['id'=>'2 ','municipio'=>'LA CHORRERA','id_dpto'=>'1'],
            ['id'=>'3 ','municipio'=>'LA PEDRERA','id_dpto'=>'1'],
            ['id'=>'4 ','municipio'=>'LA VICTORIA','id_dpto'=>'1'],
            ['id'=>'5 ','municipio'=>'LETICIA','id_dpto'=>'1'],
            ['id'=>'6 ','municipio'=>'MIRITI','id_dpto'=>'1'],
            ['id'=>'7 ','municipio'=>'PUERTO ALEGRIA','id_dpto'=>'1'],
            ['id'=>'8 ','municipio'=>'PUERTO ARICA','id_dpto'=>'1'],
            ['id'=>'9 ','municipio'=>'PUERTO NARIÑO ','id_dpto'=>'1'],
            ['id'=>'10','municipio'=>'PUERTO SANTANDER ','id_dpto'=>'1'],
            ['id'=>'11','municipio'=>'TURAPACA ','id_dpto'=>'1'],
            ['id'=>'12','municipio'=>'ABEJORRAL ','id_dpto'=>'2'],
            ['id'=>'13','municipio'=>'ABRIAQUI ','id_dpto'=>'2'],
            ['id'=>'14','municipio'=>'ALEJANDRIA ','id_dpto'=>'2'],
            ['id'=>'15','municipio'=>'AMAGA ','id_dpto'=>'2'],
            ['id'=>'16','municipio'=>'AMALFI ','id_dpto'=>'2'],
            ['id'=>'17','municipio'=>'ANDES ','id_dpto'=>'2'],
            ['id'=>'18','municipio'=>'ANGELOPOLIS ','id_dpto'=>'2'],
            ['id'=>'19','municipio'=>'ANGOSTURA ','id_dpto'=>'2'],
            ['id'=>'20','municipio'=>'ANORI ','id_dpto'=>'2'],
            ['id'=>'21','municipio'=>'ANTIOQUIA ','id_dpto'=>'2'],
            ['id'=>'22','municipio'=>'ANZA ','id_dpto'=>'2'],
            ['id'=>'23','municipio'=>'APARTADO ','id_dpto'=>'2'],
            ['id'=>'24','municipio'=>'ARBOLETES ','id_dpto'=>'2'],
            ['id'=>'25','municipio'=>'ARGELIA ','id_dpto'=>'2'],
            ['id'=>'26','municipio'=>'ARMENIA ','id_dpto'=>'2'],
            ['id'=>'27','municipio'=>'BARBOSA ','id_dpto'=>'2'],
            ['id'=>'28','municipio'=>'BELLO ','id_dpto'=>'2'],
            ['id'=>'29','municipio'=>'BELMIRA ','id_dpto'=>'2'],
            ['id'=>'30','municipio'=>'BETANIA ','id_dpto'=>'2'],
            ['id'=>'31','municipio'=>'BETULIA ','id_dpto'=>'2'],
            ['id'=>'32','municipio'=>'BOLIVAR ','id_dpto'=>'2'],
            ['id'=>'33','municipio'=>'BRICEÑO ','id_dpto'=>'2'],
            ['id'=>'34','municipio'=>'BURITICA ','id_dpto'=>'2'],
            ['id'=>'35','municipio'=>'CACERES ','id_dpto'=>'2'],
            ['id'=>'36','municipio'=>'CAICEDO ','id_dpto'=>'2'],
            ['id'=>'37','municipio'=>'CALDAS ','id_dpto'=>'2'],
            ['id'=>'38','municipio'=>'CAMPAMENTO ','id_dpto'=>'2'],
            ['id'=>'39','municipio'=>'CANASGORDAS ','id_dpto'=>'2'],
            ['id'=>'40','municipio'=>'CARACOLI ','id_dpto'=>'2'],
            ['id'=>'41','municipio'=>'CARAMANTA ','id_dpto'=>'2'],
            ['id'=>'42','municipio'=>'CAREPA ','id_dpto'=>'2'],
            ['id'=>'43','municipio'=>'CARMEN DE VIBORAL ','id_dpto'=>'2'],
            ['id'=>'44','municipio'=>'CAROLINA DEL PRINCIPE ','id_dpto'=>'2'],
            ['id'=>'45','municipio'=>'CAUCASIA ','id_dpto'=>'2'],
            ['id'=>'46','municipio'=>'CHIGORODO ','id_dpto'=>'2'],
            ['id'=>'47','municipio'=>'CISNEROS ','id_dpto'=>'2'],
            ['id'=>'48','municipio'=>'COCORNA ','id_dpto'=>'2'],
            ['id'=>'49','municipio'=>'CONCEPCION ','id_dpto'=>'2'],
            ['id'=>'50','municipio'=>'CONCORDIA ','id_dpto'=>'2'],
            ['id'=>'51','municipio'=>'COPACABANA ','id_dpto'=>'2'],
            ['id'=>'52','municipio'=>'DABEIBA ','id_dpto'=>'2'],
            ['id'=>'53','municipio'=>'DONMATIAS ','id_dpto'=>'2'],
            ['id'=>'54','municipio'=>'EBEJICO ','id_dpto'=>'2'],
            ['id'=>'55','municipio'=>'EL BAGRE ','id_dpto'=>'2'],
            ['id'=>'56','municipio'=>'EL PENOL ','id_dpto'=>'2'],
            ['id'=>'57','municipio'=>'EL RETIRO ','id_dpto'=>'2'],
            ['id'=>'58','municipio'=>'ENTRERRIOS ','id_dpto'=>'2'],
            ['id'=>'59','municipio'=>'ENVIGADO ','id_dpto'=>'2'],
            ['id'=>'60','municipio'=>'FREDONIA ','id_dpto'=>'2'],
            ['id'=>'61','municipio'=>'FRONTINO ','id_dpto'=>'2'],
            ['id'=>'62','municipio'=>'GIRALDO ','id_dpto'=>'2'],
            ['id'=>'63','municipio'=>'GIRARDOTA ','id_dpto'=>'2'],
            ['id'=>'64','municipio'=>'GOMEZ PLATA ','id_dpto'=>'2'],
            ['id'=>'65','municipio'=>'GRANADA ','id_dpto'=>'2'],
            ['id'=>'66','municipio'=>'GUADALUPE ','id_dpto'=>'2'],
            ['id'=>'67','municipio'=>'GUARNE ','id_dpto'=>'2'],
            ['id'=>'68','municipio'=>'GUATAQUE ','id_dpto'=>'2'],
            ['id'=>'69','municipio'=>'HELICONIA ','id_dpto'=>'2'],
            ['id'=>'70','municipio'=>'HISPANIA ','id_dpto'=>'2'],
            ['id'=>'71','municipio'=>'ITAGUI ','id_dpto'=>'2'],
            ['id'=>'72','municipio'=>'ITUANGO ','id_dpto'=>'2'],
            ['id'=>'73','municipio'=>'JARDIN ','id_dpto'=>'2'],
            ['id'=>'74','municipio'=>'JERICO ','id_dpto'=>'2'],
            ['id'=>'75','municipio'=>'LA CEJA ','id_dpto'=>'2'],
            ['id'=>'76','municipio'=>'LA ESTRELLA ','id_dpto'=>'2'],
            ['id'=>'77','municipio'=>'LA PINTADA ','id_dpto'=>'2'],
            ['id'=>'78','municipio'=>'LA UNION ','id_dpto'=>'2'],
            ['id'=>'79','municipio'=>'LIBORINA ','id_dpto'=>'2'],
            ['id'=>'80','municipio'=>'MACEO ','id_dpto'=>'2'],
            ['id'=>'81','municipio'=>'MARINILLA ','id_dpto'=>'2'],
            ['id'=>'82','municipio'=>'MEDELLIN ','id_dpto'=>'2'],
            ['id'=>'83','municipio'=>'MONTEBELLO ','id_dpto'=>'2'],
            ['id'=>'84','municipio'=>'MURINDO ','id_dpto'=>'2'],
            ['id'=>'85','municipio'=>'MUTATA ','id_dpto'=>'2'],
            ['id'=>'86','municipio'=>'NARINO ','id_dpto'=>'2'],
            ['id'=>'87','municipio'=>'NECHI ','id_dpto'=>'2'],
            ['id'=>'88','municipio'=>'NECOCLI ','id_dpto'=>'2'],
            ['id'=>'89','municipio'=>'OLAYA ','id_dpto'=>'2'],
            ['id'=>'90','municipio'=>'PEQUE ','id_dpto'=>'2'],
            ['id'=>'91','municipio'=>'PUEBLORRICO ','id_dpto'=>'2'],
            ['id'=>'92','municipio'=>'PUERTO BERRIO ','id_dpto'=>'2'],
            ['id'=>'93','municipio'=>'PUERTO NARE ','id_dpto'=>'2'],
            ['id'=>'94','municipio'=>'PUERTO TRIUNFO ','id_dpto'=>'2'],
            ['id'=>'95','municipio'=>'REMEDIOS ','id_dpto'=>'2'],
            ['id'=>'96','municipio'=>'RIONEGRO ','id_dpto'=>'2'],
            ['id'=>'97','municipio'=>'SABANALARGA ','id_dpto'=>'2'],
            ['id'=>'98','municipio'=>'SABANETA ','id_dpto'=>'2'],
            ['id'=>'99','municipio'=>'SALGAR ','id_dpto'=>'2'],
            ['id'=>'100 ','municipio'=>'SAN ANDRES DE CUERQUIA','id_dpto'=>'2'],
            ['id'=>'101 ','municipio'=>'SAN CARLOS','id_dpto'=>'2'],
            ['id'=>'102 ','municipio'=>'SAN FRANCISCO','id_dpto'=>'2'],
            ['id'=>'103 ','municipio'=>'SAN JERONIMO','id_dpto'=>'2'],
            ['id'=>'104 ','municipio'=>'SAN JOSE DE LA MONTAÑA','id_dpto'=>'2'],
            ['id'=>'105 ','municipio'=>'SAN JUAN DE URABA','id_dpto'=>'2'],
            ['id'=>'106 ','municipio'=>'SAN LUIS','id_dpto'=>'2'],
            ['id'=>'107 ','municipio'=>'SAN PEDRO DE LOS MILAGROS','id_dpto'=>'2'],
            ['id'=>'108 ','municipio'=>'SAN PEDRO DE URABA','id_dpto'=>'2'],
            ['id'=>'109 ','municipio'=>'SAN RAFAEL','id_dpto'=>'2'],
            ['id'=>'110 ','municipio'=>'SAN ROQUE','id_dpto'=>'2'],
            ['id'=>'111 ','municipio'=>'SAN VICENTE','id_dpto'=>'2'],
            ['id'=>'112 ','municipio'=>'SANTA BARBARA','id_dpto'=>'2'],
            ['id'=>'113 ','municipio'=>'SANTA ROSA DE OSOS','id_dpto'=>'2'],
            ['id'=>'114 ','municipio'=>'SANTO DOMINGO','id_dpto'=>'2'],
            ['id'=>'115 ','municipio'=>'SANTUARIO','id_dpto'=>'2'],
            ['id'=>'116 ','municipio'=>'SEGOVIA','id_dpto'=>'2'],
            ['id'=>'117 ','municipio'=>'SONSON','id_dpto'=>'2'],
            ['id'=>'118 ','municipio'=>'SOPETRAN','id_dpto'=>'2'],
            ['id'=>'119 ','municipio'=>'TAMESIS','id_dpto'=>'2'],
            ['id'=>'120 ','municipio'=>'TARAZA','id_dpto'=>'2'],
            ['id'=>'121 ','municipio'=>'TARSO','id_dpto'=>'2'],
            ['id'=>'122 ','municipio'=>'TITIRIBI','id_dpto'=>'2'],
            ['id'=>'123 ','municipio'=>'TOLEDO','id_dpto'=>'2'],
            ['id'=>'124 ','municipio'=>'TURBO','id_dpto'=>'2'],
            ['id'=>'125 ','municipio'=>'URAMITA','id_dpto'=>'2'],
            ['id'=>'126 ','municipio'=>'URRAO','id_dpto'=>'2'],
            ['id'=>'127 ','municipio'=>'VALDIVIA','id_dpto'=>'2'],
            ['id'=>'128 ','municipio'=>'VALPARAISO','id_dpto'=>'2'],
            ['id'=>'129 ','municipio'=>'VEGACHI','id_dpto'=>'2'],
            ['id'=>'130 ','municipio'=>'VENECIA','id_dpto'=>'2'],
            ['id'=>'131 ','municipio'=>'VIGIA DEL FUERTE','id_dpto'=>'2'],
            ['id'=>'132 ','municipio'=>'YALI','id_dpto'=>'2'],
            ['id'=>'133 ','municipio'=>'YARUMAL','id_dpto'=>'2'],
            ['id'=>'134 ','municipio'=>'YOLOMBO','id_dpto'=>'2'],
            ['id'=>'135 ','municipio'=>'YONDO','id_dpto'=>'2'],
            ['id'=>'136 ','municipio'=>'ZARAGOZA','id_dpto'=>'2'],
            ['id'=>'137 ','municipio'=>'ARAUCA','id_dpto'=>'3'],
            ['id'=>'138 ','municipio'=>'ARAUQUITA','id_dpto'=>'3'],
            ['id'=>'139 ','municipio'=>'CRAVO NORTE','id_dpto'=>'3'],
            ['id'=>'140 ','municipio'=>'FORTUL','id_dpto'=>'3'],
            ['id'=>'141 ','municipio'=>'PUERTO RONDON','id_dpto'=>'3'],
            ['id'=>'142 ','municipio'=>'SARAVENA','id_dpto'=>'3'],
            ['id'=>'143 ','municipio'=>'TAME','id_dpto'=>'3'],
            ['id'=>'144 ','municipio'=>'BARANOA','id_dpto'=>'4'],
            ['id'=>'145 ','municipio'=>'BARRANQUILLA','id_dpto'=>'4'],
            ['id'=>'146 ','municipio'=>'CAMPO DE LA CRUZ','id_dpto'=>'4'],
            ['id'=>'147 ','municipio'=>'CANDELARIA','id_dpto'=>'4'],
            ['id'=>'148 ','municipio'=>'GALAPA','id_dpto'=>'4'],
            ['id'=>'149 ','municipio'=>'JUAN DE ACOSTA','id_dpto'=>'4'],
            ['id'=>'150 ','municipio'=>'LURUACO','id_dpto'=>'4'],
            ['id'=>'151 ','municipio'=>'MALAMBO','id_dpto'=>'4'],
            ['id'=>'152 ','municipio'=>'MANATI','id_dpto'=>'4'],
            ['id'=>'153 ','municipio'=>'PALMAR DE VARELA','id_dpto'=>'4'],
            ['id'=>'154 ','municipio'=>'PIOJO','id_dpto'=>'4'],
            ['id'=>'155 ','municipio'=>'POLO NUEVO','id_dpto'=>'4'],
            ['id'=>'156 ','municipio'=>'PONEDERA','id_dpto'=>'4'],
            ['id'=>'157 ','municipio'=>'PUERTO COLOMBIA','id_dpto'=>'4'],
            ['id'=>'158 ','municipio'=>'REPELON','id_dpto'=>'4'],
            ['id'=>'159 ','municipio'=>'SABANAGRANDE','id_dpto'=>'4'],
            ['id'=>'160 ','municipio'=>'SABANALARGA','id_dpto'=>'4'],
            ['id'=>'161 ','municipio'=>'SANTA LUCIA','id_dpto'=>'4'],
            ['id'=>'162 ','municipio'=>'SANTO TOMAS','id_dpto'=>'4'],
            ['id'=>'163 ','municipio'=>'SOLEDAD','id_dpto'=>'4'],
            ['id'=>'164 ','municipio'=>'SUAN','id_dpto'=>'4'],
            ['id'=>'165 ','municipio'=>'TUBARA','id_dpto'=>'4'],
            ['id'=>'166 ','municipio'=>'USIACURI','id_dpto'=>'4'],
            ['id'=>'167 ','municipio'=>'ACHI','id_dpto'=>'5'],
            ['id'=>'168 ','municipio'=>'ALTOS DEL ROSARIO','id_dpto'=>'5'],
            ['id'=>'169 ','municipio'=>'ARENAL','id_dpto'=>'5'],
            ['id'=>'170 ','municipio'=>'ARJONA','id_dpto'=>'5'],
            ['id'=>'171 ','municipio'=>'ARROYOHONDO','id_dpto'=>'5'],
            ['id'=>'172 ','municipio'=>'BARRANCO DE LOBA','id_dpto'=>'5'],
            ['id'=>'173 ','municipio'=>'BRAZUELO DE PAPAYAL','id_dpto'=>'5'],
            ['id'=>'174 ','municipio'=>'CALAMAR','id_dpto'=>'5'],
            ['id'=>'175 ','municipio'=>'CANTAGALLO','id_dpto'=>'5'],
            ['id'=>'176 ','municipio'=>'CARTAGENA DE INDIAS','id_dpto'=>'5'],
            ['id'=>'177 ','municipio'=>'CICUCO','id_dpto'=>'5'],
            ['id'=>'178 ','municipio'=>'CLEMENCIA','id_dpto'=>'5'],
            ['id'=>'179 ','municipio'=>'CORDOBA','id_dpto'=>'5'],
            ['id'=>'180 ','municipio'=>'EL CARMEN DE BOLIVAR','id_dpto'=>'5'],
            ['id'=>'181 ','municipio'=>'EL GUAMO','id_dpto'=>'5'],
            ['id'=>'182 ','municipio'=>'EL PENION','id_dpto'=>'5'],
            ['id'=>'183 ','municipio'=>'HATILLO DE LOBA','id_dpto'=>'5'],
            ['id'=>'184 ','municipio'=>'MAGANGUE','id_dpto'=>'5'],
            ['id'=>'185 ','municipio'=>'MAHATES','id_dpto'=>'5'],
            ['id'=>'186 ','municipio'=>'MARGARITA','id_dpto'=>'5'],
            ['id'=>'187 ','municipio'=>'MARIA LA BAJA','id_dpto'=>'5'],
            ['id'=>'188 ','municipio'=>'MONTECRISTO','id_dpto'=>'5'],
            ['id'=>'189 ','municipio'=>'MORALES','id_dpto'=>'5'],
            ['id'=>'190 ','municipio'=>'MORALES','id_dpto'=>'5'],
            ['id'=>'191 ','municipio'=>'NOROSI','id_dpto'=>'5'],
            ['id'=>'192 ','municipio'=>'PINILLOS','id_dpto'=>'5'],
            ['id'=>'193 ','municipio'=>'REGIDOR','id_dpto'=>'5'],
            ['id'=>'194 ','municipio'=>'RIO VIEJO','id_dpto'=>'5'],
            ['id'=>'195 ','municipio'=>'SAN CRISTOBAL','id_dpto'=>'5'],
            ['id'=>'196 ','municipio'=>'SAN ESTANISLAO','id_dpto'=>'5'],
            ['id'=>'197 ','municipio'=>'SAN FERNANDO','id_dpto'=>'5'],
            ['id'=>'198 ','municipio'=>'SAN JACINTO','id_dpto'=>'5'],
            ['id'=>'199 ','municipio'=>'SAN JACINTO DEL CAUCA','id_dpto'=>'5'],
            ['id'=>'200 ','municipio'=>'SAN JUAN DE NEPOMUCENO','id_dpto'=>'5'],
            ['id'=>'201 ','municipio'=>'SAN MARTIN DE LOBA','id_dpto'=>'5'],
            ['id'=>'202 ','municipio'=>'SAN PABLO','id_dpto'=>'5'],
            ['id'=>'203 ','municipio'=>'SAN PABLO NORTE','id_dpto'=>'5'],
            ['id'=>'204 ','municipio'=>'SANTA CATALINA','id_dpto'=>'5'],
            ['id'=>'205 ','municipio'=>'SANTA CRUZ DE MOMPOX','id_dpto'=>'5'],
            ['id'=>'206 ','municipio'=>'SANTA ROSA','id_dpto'=>'5'],
            ['id'=>'207 ','municipio'=>'SANTA ROSA DEL SUR','id_dpto'=>'5'],
            ['id'=>'208 ','municipio'=>'SIMITI','id_dpto'=>'5'],
            ['id'=>'209 ','municipio'=>'SOPLAVIENTO','id_dpto'=>'5'],
            ['id'=>'210 ','municipio'=>'TALAIGUA NUEVO','id_dpto'=>'5'],
            ['id'=>'211 ','municipio'=>'TUQUISIO','id_dpto'=>'5'],
            ['id'=>'212 ','municipio'=>'TURBACO','id_dpto'=>'5'],
            ['id'=>'213 ','municipio'=>'TURBANA','id_dpto'=>'5'],
            ['id'=>'214 ','municipio'=>'VILLANUEVA','id_dpto'=>'5'],
            ['id'=>'215 ','municipio'=>'ZAMBRANO','id_dpto'=>'5'],
            ['id'=>'216 ','municipio'=>'AQUITANIA','id_dpto'=>'6'],
            ['id'=>'217 ','municipio'=>'ARCABUCO','id_dpto'=>'6'],
            ['id'=>'218 ','municipio'=>'BELÉN','id_dpto'=>'6'],
            ['id'=>'219 ','municipio'=>'BERBEO','id_dpto'=>'6'],
            ['id'=>'220 ','municipio'=>'BETÉITIVA','id_dpto'=>'6'],
            ['id'=>'221 ','municipio'=>'BOAVITA','id_dpto'=>'6'],
            ['id'=>'222 ','municipio'=>'BOYACÁ','id_dpto'=>'6'],
            ['id'=>'223 ','municipio'=>'BRICEÑO','id_dpto'=>'6'],
            ['id'=>'224 ','municipio'=>'BUENAVISTA','id_dpto'=>'6'],
            ['id'=>'225 ','municipio'=>'BUSBANZÁ','id_dpto'=>'6'],
            ['id'=>'226 ','municipio'=>'CALDAS','id_dpto'=>'6'],
            ['id'=>'227 ','municipio'=>'CAMPO HERMOSO','id_dpto'=>'6'],
            ['id'=>'228 ','municipio'=>'CERINZA','id_dpto'=>'6'],
            ['id'=>'229 ','municipio'=>'CHINAVITA','id_dpto'=>'6'],
            ['id'=>'230 ','municipio'=>'CHIQUINQUIRÁ','id_dpto'=>'6'],
            ['id'=>'231 ','municipio'=>'CHÍQUIZA','id_dpto'=>'6'],
            ['id'=>'232 ','municipio'=>'CHISCAS','id_dpto'=>'6'],
            ['id'=>'233 ','municipio'=>'CHITA','id_dpto'=>'6'],
            ['id'=>'234 ','municipio'=>'CHITARAQUE','id_dpto'=>'6'],
            ['id'=>'235 ','municipio'=>'CHIVATÁ','id_dpto'=>'6'],
            ['id'=>'236 ','municipio'=>'CIÉNEGA','id_dpto'=>'6'],
            ['id'=>'237 ','municipio'=>'CÓMBITA','id_dpto'=>'6'],
            ['id'=>'238 ','municipio'=>'COPER','id_dpto'=>'6'],
            ['id'=>'239 ','municipio'=>'CORRALES','id_dpto'=>'6'],
            ['id'=>'240 ','municipio'=>'COVARACHÍA','id_dpto'=>'6'],
            ['id'=>'241 ','municipio'=>'CUBARA','id_dpto'=>'6'],
            ['id'=>'242 ','municipio'=>'CUCAITA','id_dpto'=>'6'],
            ['id'=>'243 ','municipio'=>'CUITIVA','id_dpto'=>'6'],
            ['id'=>'244 ','municipio'=>'DUITAMA','id_dpto'=>'6'],
            ['id'=>'245 ','municipio'=>'EL COCUY','id_dpto'=>'6'],
            ['id'=>'246 ','municipio'=>'EL ESPINO','id_dpto'=>'6'],
            ['id'=>'247 ','municipio'=>'FIRAVITOBA','id_dpto'=>'6'],
            ['id'=>'248 ','municipio'=>'FLORESTA','id_dpto'=>'6'],
            ['id'=>'249 ','municipio'=>'GACHANTIVÁ','id_dpto'=>'6'],
            ['id'=>'250 ','municipio'=>'GÁMEZA','id_dpto'=>'6'],
            ['id'=>'251 ','municipio'=>'GARAGOA','id_dpto'=>'6'],
            ['id'=>'252 ','municipio'=>'GUACAMAYAS','id_dpto'=>'6'],
            ['id'=>'253 ','municipio'=>'GÜICÁN','id_dpto'=>'6'],
            ['id'=>'254 ','municipio'=>'IZA','id_dpto'=>'6'],
            ['id'=>'255 ','municipio'=>'JENESANO','id_dpto'=>'6'],
            ['id'=>'256 ','municipio'=>'JERICÓ','id_dpto'=>'6'],
            ['id'=>'257 ','municipio'=>'LA UVITA','id_dpto'=>'6'],
            ['id'=>'258 ','municipio'=>'LA VICTORIA','id_dpto'=>'6'],
            ['id'=>'259 ','municipio'=>'LABRANZA GRANDE','id_dpto'=>'6'],
            ['id'=>'260 ','municipio'=>'MACANAL','id_dpto'=>'6'],
            ['id'=>'261 ','municipio'=>'MARIPÍ','id_dpto'=>'6'],
            ['id'=>'262 ','municipio'=>'MIRAFLORES','id_dpto'=>'6'],
            ['id'=>'263 ','municipio'=>'MONGUA','id_dpto'=>'6'],
            ['id'=>'264 ','municipio'=>'MONGUÍ','id_dpto'=>'6'],
            ['id'=>'265 ','municipio'=>'MONIQUIRÁ','id_dpto'=>'6'],
            ['id'=>'266 ','municipio'=>'MOTAVITA','id_dpto'=>'6'],
            ['id'=>'267 ','municipio'=>'MUZO','id_dpto'=>'6'],
            ['id'=>'268 ','municipio'=>'NOBSA','id_dpto'=>'6'],
            ['id'=>'269 ','municipio'=>'NUEVO COLÓN','id_dpto'=>'6'],
            ['id'=>'270 ','municipio'=>'OICATÁ','id_dpto'=>'6'],
            ['id'=>'271 ','municipio'=>'OTANCHE','id_dpto'=>'6'],
            ['id'=>'272 ','municipio'=>'PACHAVITA','id_dpto'=>'6'],
            ['id'=>'273 ','municipio'=>'PÁEZ','id_dpto'=>'6'],
            ['id'=>'274 ','municipio'=>'PAIPA','id_dpto'=>'6'],
            ['id'=>'275 ','municipio'=>'PAJARITO','id_dpto'=>'6'],
            ['id'=>'276 ','municipio'=>'PANQUEBA','id_dpto'=>'6'],
            ['id'=>'277 ','municipio'=>'PAUNA','id_dpto'=>'6'],
            ['id'=>'278 ','municipio'=>'PAYA','id_dpto'=>'6'],
            ['id'=>'279 ','municipio'=>'PAZ DE RÍO','id_dpto'=>'6'],
            ['id'=>'280 ','municipio'=>'PESCA','id_dpto'=>'6'],
            ['id'=>'281 ','municipio'=>'PISBA','id_dpto'=>'6'],
            ['id'=>'282 ','municipio'=>'PUERTO BOYACA','id_dpto'=>'6'],
            ['id'=>'283 ','municipio'=>'QUÍPAMA','id_dpto'=>'6'],
            ['id'=>'284 ','municipio'=>'RAMIRIQUÍ','id_dpto'=>'6'],
            ['id'=>'285 ','municipio'=>'RÁQUIRA','id_dpto'=>'6'],
            ['id'=>'286 ','municipio'=>'RONDÓN','id_dpto'=>'6'],
            ['id'=>'287 ','municipio'=>'SABOYÁ','id_dpto'=>'6'],
            ['id'=>'288 ','municipio'=>'SÁCHICA','id_dpto'=>'6'],
            ['id'=>'289 ','municipio'=>'SAMACÁ','id_dpto'=>'6'],
            ['id'=>'290 ','municipio'=>'SAN EDUARDO','id_dpto'=>'6'],
            ['id'=>'291 ','municipio'=>'SAN JOSÉ DE PARE','id_dpto'=>'6'],
            ['id'=>'292 ','municipio'=>'SAN LUÍS DE GACENO','id_dpto'=>'6'],
            ['id'=>'293 ','municipio'=>'SAN MATEO','id_dpto'=>'6'],
            ['id'=>'294 ','municipio'=>'SAN MIGUEL DE SEMA','id_dpto'=>'6'],
            ['id'=>'295 ','municipio'=>'SAN PABLO DE BORBUR','id_dpto'=>'6'],
            ['id'=>'296 ','municipio'=>'SANTA MARÍA','id_dpto'=>'6'],
            ['id'=>'297 ','municipio'=>'SANTA ROSA DE VITERBO','id_dpto'=>'6'],
            ['id'=>'298 ','municipio'=>'SANTA SOFÍA','id_dpto'=>'6'],
            ['id'=>'299 ','municipio'=>'SANTANA','id_dpto'=>'6'],
            ['id'=>'300 ','municipio'=>'SATIVANORTE','id_dpto'=>'6'],
            ['id'=>'301 ','municipio'=>'SATIVASUR','id_dpto'=>'6'],
            ['id'=>'302 ','municipio'=>'SIACHOQUE','id_dpto'=>'6'],
            ['id'=>'303 ','municipio'=>'SOATÁ','id_dpto'=>'6'],
            ['id'=>'304 ','municipio'=>'SOCHA','id_dpto'=>'6'],
            ['id'=>'305 ','municipio'=>'SOCOTÁ','id_dpto'=>'6'],
            ['id'=>'306 ','municipio'=>'SOGAMOSO','id_dpto'=>'6'],
            ['id'=>'307 ','municipio'=>'SORA','id_dpto'=>'6'],
            ['id'=>'308 ','municipio'=>'SORACÁ','id_dpto'=>'6'],
            ['id'=>'309 ','municipio'=>'SOTAQUIRÁ','id_dpto'=>'6'],
            ['id'=>'310 ','municipio'=>'SUSACÓN','id_dpto'=>'6'],
            ['id'=>'311 ','municipio'=>'SUTARMACHÁN','id_dpto'=>'6'],
            ['id'=>'312 ','municipio'=>'TASCO','id_dpto'=>'6'],
            ['id'=>'313 ','municipio'=>'TIBANÁ','id_dpto'=>'6'],
            ['id'=>'314 ','municipio'=>'TIBASOSA','id_dpto'=>'6'],
            ['id'=>'315 ','municipio'=>'TINJACÁ','id_dpto'=>'6'],
            ['id'=>'316 ','municipio'=>'TIPACOQUE','id_dpto'=>'6'],
            ['id'=>'317 ','municipio'=>'TOCA','id_dpto'=>'6'],
            ['id'=>'318 ','municipio'=>'TOGÜÍ','id_dpto'=>'6'],
            ['id'=>'319 ','municipio'=>'TÓPAGA','id_dpto'=>'6'],
            ['id'=>'320 ','municipio'=>'TOTA','id_dpto'=>'6'],
            ['id'=>'321 ','municipio'=>'TUNJA','id_dpto'=>'6'],
            ['id'=>'322 ','municipio'=>'TUNUNGUÁ','id_dpto'=>'6'],
            ['id'=>'323 ','municipio'=>'TURMEQUÉ','id_dpto'=>'6'],
            ['id'=>'324 ','municipio'=>'TUTA','id_dpto'=>'6'],
            ['id'=>'325 ','municipio'=>'TUTAZÁ','id_dpto'=>'6'],
            ['id'=>'326 ','municipio'=>'UMBITA','id_dpto'=>'6'],
            ['id'=>'327 ','municipio'=>'VENTA QUEMADA','id_dpto'=>'6'],
            ['id'=>'328 ','municipio'=>'VILLA DE LEYVA','id_dpto'=>'6'],
            ['id'=>'329 ','municipio'=>'VIRACACHÁ','id_dpto'=>'6'],
            ['id'=>'330 ','municipio'=>'ZETAQUIRA','id_dpto'=>'6'],
            ['id'=>'331 ','municipio'=>'AGUADAS','id_dpto'=>'7'],
            ['id'=>'332 ','municipio'=>'ANSERMA','id_dpto'=>'7'],
            ['id'=>'333 ','municipio'=>'ARANZAZU','id_dpto'=>'7'],
            ['id'=>'334 ','municipio'=>'BELALCAZAR','id_dpto'=>'7'],
            ['id'=>'335 ','municipio'=>'CHINCHINÁ','id_dpto'=>'7'],
            ['id'=>'336 ','municipio'=>'FILADELFIA','id_dpto'=>'7'],
            ['id'=>'337 ','municipio'=>'LA DORADA','id_dpto'=>'7'],
            ['id'=>'338 ','municipio'=>'LA MERCED','id_dpto'=>'7'],
            ['id'=>'339 ','municipio'=>'MANIZALES','id_dpto'=>'7'],
            ['id'=>'340 ','municipio'=>'MANZANARES','id_dpto'=>'7'],
            ['id'=>'341 ','municipio'=>'MARMATO','id_dpto'=>'7'],
            ['id'=>'342 ','municipio'=>'MARQUETALIA','id_dpto'=>'7'],
            ['id'=>'343 ','municipio'=>'MARULANDA','id_dpto'=>'7'],
            ['id'=>'344 ','municipio'=>'NEIRA','id_dpto'=>'7'],
            ['id'=>'345 ','municipio'=>'NORCASIA','id_dpto'=>'7'],
            ['id'=>'346 ','municipio'=>'PACORA','id_dpto'=>'7'],
            ['id'=>'347 ','municipio'=>'PALESTINA','id_dpto'=>'7'],
            ['id'=>'348 ','municipio'=>'PENSILVANIA','id_dpto'=>'7'],
            ['id'=>'349 ','municipio'=>'RIOSUCIO','id_dpto'=>'7'],
            ['id'=>'350 ','municipio'=>'RISARALDA','id_dpto'=>'7'],
            ['id'=>'351 ','municipio'=>'SALAMINA','id_dpto'=>'7'],
            ['id'=>'352 ','municipio'=>'SAMANA','id_dpto'=>'7'],
            ['id'=>'353 ','municipio'=>'SAN JOSE','id_dpto'=>'7'],
            ['id'=>'354 ','municipio'=>'SUPÍA','id_dpto'=>'7'],
            ['id'=>'355 ','municipio'=>'VICTORIA','id_dpto'=>'7'],
            ['id'=>'356 ','municipio'=>'VILLAMARÍA','id_dpto'=>'7'],
            ['id'=>'357 ','municipio'=>'VITERBO','id_dpto'=>'7'],
            ['id'=>'358 ','municipio'=>'ALBANIA','id_dpto'=>'8'],
            ['id'=>'359 ','municipio'=>'BELÉN ANDAQUIES','id_dpto'=>'8'],
            ['id'=>'360 ','municipio'=>'CARTAGENA DEL CHAIRA','id_dpto'=>'8'],
            ['id'=>'361 ','municipio'=>'CURILLO','id_dpto'=>'8'],
            ['id'=>'362 ','municipio'=>'EL DONCELLO','id_dpto'=>'8'],
            ['id'=>'363 ','municipio'=>'EL PAUJIL','id_dpto'=>'8'],
            ['id'=>'364 ','municipio'=>'FLORENCIA','id_dpto'=>'8'],
            ['id'=>'365 ','municipio'=>'LA MONTAÑITA','id_dpto'=>'8'],
            ['id'=>'366 ','municipio'=>'MILÁN','id_dpto'=>'8'],
            ['id'=>'367 ','municipio'=>'MORELIA','id_dpto'=>'8'],
            ['id'=>'368 ','municipio'=>'PUERTO RICO','id_dpto'=>'8'],
            ['id'=>'369 ','municipio'=>'SANVICENTE DEL CAGUAN','id_dpto'=>'8'],
            ['id'=>'370 ','municipio'=>'SAN JOSÉ DE FRAGUA','id_dpto'=>'8'],
            ['id'=>'371 ','municipio'=>'SOLANO','id_dpto'=>'8'],
            ['id'=>'372 ','municipio'=>'SOLITA','id_dpto'=>'8'],
            ['id'=>'373 ','municipio'=>'VALPARAÍSO','id_dpto'=>'8'],
            ['id'=>'374 ','municipio'=>'AGUAZUL','id_dpto'=>'9'],
            ['id'=>'375 ','municipio'=>'CHAMEZA','id_dpto'=>'9'],
            ['id'=>'376 ','municipio'=>'HATO COROZAL','id_dpto'=>'9'],
            ['id'=>'377 ','municipio'=>'LA SALINA','id_dpto'=>'9'],
            ['id'=>'378 ','municipio'=>'MANÍ','id_dpto'=>'9'],
            ['id'=>'379 ','municipio'=>'MONTERREY','id_dpto'=>'9'],
            ['id'=>'380 ','municipio'=>'NUNCHIA','id_dpto'=>'9'],
            ['id'=>'381 ','municipio'=>'OROCUE','id_dpto'=>'9'],
            ['id'=>'382 ','municipio'=>'PAZ DE ARIPORO','id_dpto'=>'9'],
            ['id'=>'383 ','municipio'=>'PORE','id_dpto'=>'9'],
            ['id'=>'384 ','municipio'=>'RECETOR','id_dpto'=>'9'],
            ['id'=>'385 ','municipio'=>'SABANA LARGA','id_dpto'=>'9'],
            ['id'=>'386 ','municipio'=>'SACAMA','id_dpto'=>'9'],
            ['id'=>'387 ','municipio'=>'SAN LUIS DE PALENQUE','id_dpto'=>'9'],
            ['id'=>'388 ','municipio'=>'TAMARA','id_dpto'=>'9'],
            ['id'=>'389 ','municipio'=>'TAURAMENA','id_dpto'=>'9'],
            ['id'=>'390 ','municipio'=>'TRINIDAD','id_dpto'=>'9'],
            ['id'=>'391 ','municipio'=>'VILLANUEVA','id_dpto'=>'9'],
            ['id'=>'392 ','municipio'=>'YOPAL','id_dpto'=>'9'],
            ['id'=>'393 ','municipio'=>'ALMAGUER' ,'id_dpto'=>'10'],
            ['id'=>'394 ','municipio'=>'ARGELIA' ,'id_dpto'=>'10'],
            ['id'=>'395 ','municipio'=>'BALBOA' ,'id_dpto'=>'10'],
            ['id'=>'396 ','municipio'=>'BOLÍVAR' ,'id_dpto'=>'10'],
            ['id'=>'397 ','municipio'=>'BUENOS AIRES' ,'id_dpto'=>'10'],
            ['id'=>'398 ','municipio'=>'CAJIBIO' ,'id_dpto'=>'10'],
            ['id'=>'399 ','municipio'=>'CALDONO' ,'id_dpto'=>'10'],
            ['id'=>'400 ','municipio'=>'CALOTO' ,'id_dpto'=>'10'],
            ['id'=>'401 ','municipio'=>'CORINTO' ,'id_dpto'=>'10'],
            ['id'=>'402 ','municipio'=>'EL TAMBO' ,'id_dpto'=>'10'],
            ['id'=>'403 ','municipio'=>'FLORENCIA' ,'id_dpto'=>'10'],
            ['id'=>'404 ','municipio'=>'GUAPI' ,'id_dpto'=>'10'],
            ['id'=>'405 ','municipio'=>'INZA' ,'id_dpto'=>'10'],
            ['id'=>'406 ','municipio'=>'JAMBALÓ' ,'id_dpto'=>'10'],
            ['id'=>'407 ','municipio'=>'LA SIERRA' ,'id_dpto'=>'10'],
            ['id'=>'408 ','municipio'=>'LA VEGA' ,'id_dpto'=>'10'],
            ['id'=>'409 ','municipio'=>'LÓPEZ' ,'id_dpto'=>'10'],
            ['id'=>'410 ','municipio'=>'MERCADERES' ,'id_dpto'=>'10'],
            ['id'=>'411 ','municipio'=>'MIRANDA' ,'id_dpto'=>'10'],
            ['id'=>'412 ','municipio'=>'MORALES' ,'id_dpto'=>'10'],
            ['id'=>'413 ','municipio'=>'PADILLA' ,'id_dpto'=>'10'],
            ['id'=>'414 ','municipio'=>'PÁEZ' ,'id_dpto'=>'10'],
            ['id'=>'415 ','municipio'=>'PATIA (EL BORDO)' ,'id_dpto'=>'10'],
            ['id'=>'416 ','municipio'=>'PIAMONTE' ,'id_dpto'=>'10'],
            ['id'=>'417 ','municipio'=>'PIENDAMO' ,'id_dpto'=>'10'],
            ['id'=>'418 ','municipio'=>'POPAYÁN' ,'id_dpto'=>'10'],
            ['id'=>'419 ','municipio'=>'PUERTO TEJADA' ,'id_dpto'=>'10'],
            ['id'=>'420 ','municipio'=>'PURACE' ,'id_dpto'=>'10'],
            ['id'=>'421 ','municipio'=>'ROSAS' ,'id_dpto'=>'10'],
            ['id'=>'422 ','municipio'=>'SAN SEBASTIÁN' ,'id_dpto'=>'10'],
            ['id'=>'423 ','municipio'=>'SANTA ROSA' ,'id_dpto'=>'10'],
            ['id'=>'424 ','municipio'=>'SANTANDER DE QUILICHAO' ,'id_dpto'=>'10'],
            ['id'=>'425 ','municipio'=>'SILVIA' ,'id_dpto'=>'10'],
            ['id'=>'426 ','municipio'=>'SOTARA' ,'id_dpto'=>'10'],
            ['id'=>'427 ','municipio'=>'SUÁREZ' ,'id_dpto'=>'10'],
            ['id'=>'428 ','municipio'=>'SUCRE' ,'id_dpto'=>'10'],
            ['id'=>'429 ','municipio'=>'TIMBÍO' ,'id_dpto'=>'10'],
            ['id'=>'430 ','municipio'=>'TIMBIQUÍ' ,'id_dpto'=>'10'],
            ['id'=>'431 ','municipio'=>'TORIBIO' ,'id_dpto'=>'10'],
            ['id'=>'432 ','municipio'=>'TOTORO' ,'id_dpto'=>'10'],
            ['id'=>'433 ','municipio'=>'VILLA RICA' ,'id_dpto'=>'10'],
            ['id'=>'434 ','municipio'=>'AGUACHICA' ,'id_dpto'=>'11'],
            ['id'=>'435 ','municipio'=>'AGUSTÍN CODAZZI' ,'id_dpto'=>'11'],
            ['id'=>'436 ','municipio'=>'ASTREA' ,'id_dpto'=>'11'],
            ['id'=>'437 ','municipio'=>'BECERRIL' ,'id_dpto'=>'11'],
            ['id'=>'438 ','municipio'=>'BOSCONIA' ,'id_dpto'=>'11'],
            ['id'=>'439 ','municipio'=>'CHIMICHAGUA' ,'id_dpto'=>'11'],
            ['id'=>'440 ','municipio'=>'CHIRIGUANÁ' ,'id_dpto'=>'11'],
            ['id'=>'441 ','municipio'=>'CURUMANÍ' ,'id_dpto'=>'11'],
            ['id'=>'442 ','municipio'=>'EL COPEY' ,'id_dpto'=>'11'],
            ['id'=>'443 ','municipio'=>'EL PASO' ,'id_dpto'=>'11'],
            ['id'=>'444 ','municipio'=>'GAMARRA' ,'id_dpto'=>'11'],
            ['id'=>'445 ','municipio'=>'GONZÁLEZ' ,'id_dpto'=>'11'],
            ['id'=>'446 ','municipio'=>'LA GLORIA' ,'id_dpto'=>'11'],
            ['id'=>'447 ','municipio'=>'LA JAGUA IBIRICO' ,'id_dpto'=>'11'],
            ['id'=>'448 ','municipio'=>'MANAURE BALCÓN DEL CESAR' ,'id_dpto'=>'11'],
            ['id'=>'449 ','municipio'=>'PAILITAS' ,'id_dpto'=>'11'],
            ['id'=>'450 ','municipio'=>'PELAYA' ,'id_dpto'=>'11'],
            ['id'=>'451 ','municipio'=>'PUEBLO BELLO' ,'id_dpto'=>'11'],
            ['id'=>'452 ','municipio'=>'RÍO DE ORO' ,'id_dpto'=>'11'],
            ['id'=>'453 ','municipio'=>'ROBLES (LA PAZ)' ,'id_dpto'=>'11'],
            ['id'=>'454 ','municipio'=>'SAN ALBERTO' ,'id_dpto'=>'11'],
            ['id'=>'455 ','municipio'=>'SAN DIEGO' ,'id_dpto'=>'11'],
            ['id'=>'456 ','municipio'=>'SAN MARTÍN' ,'id_dpto'=>'11'],
            ['id'=>'457 ','municipio'=>'TAMALAMEQUE' ,'id_dpto'=>'11'],
            ['id'=>'458 ','municipio'=>'VALLEDUPAR' ,'id_dpto'=>'11'],
            ['id'=>'459 ','municipio'=>'ACANDI' ,'id_dpto'=>'12'],
            ['id'=>'460 ','municipio'=>'ALTO BAUDO (PIE DE PATO)' ,'id_dpto'=>'12'],
            ['id'=>'461 ','municipio'=>'ATRATO' ,'id_dpto'=>'12'],
            ['id'=>'462 ','municipio'=>'BAGADO' ,'id_dpto'=>'12'],
            ['id'=>'463 ','municipio'=>'BAHIA SOLANO (MUTIS)' ,'id_dpto'=>'12'],
            ['id'=>'464 ','municipio'=>'BAJO BAUDO (PIZARRO)' ,'id_dpto'=>'12'],
            ['id'=>'465 ','municipio'=>'BOJAYA (BELLAVISTA)' ,'id_dpto'=>'12'],
            ['id'=>'466 ','municipio'=>'CANTON DE SAN PABLO' ,'id_dpto'=>'12'],
            ['id'=>'467 ','municipio'=>'CARMEN DEL DARIEN' ,'id_dpto'=>'12'],
            ['id'=>'468 ','municipio'=>'CERTEGUI' ,'id_dpto'=>'12'],
            ['id'=>'469 ','municipio'=>'CONDOTO' ,'id_dpto'=>'12'],
            ['id'=>'470 ','municipio'=>'EL CARMEN' ,'id_dpto'=>'12'],
            ['id'=>'471 ','municipio'=>'ISTMINA' ,'id_dpto'=>'12'],
            ['id'=>'472 ','municipio'=>'JURADO' ,'id_dpto'=>'12'],
            ['id'=>'473 ','municipio'=>'LITORAL DEL SAN JUAN' ,'id_dpto'=>'12'],
            ['id'=>'474 ','municipio'=>'LLORO' ,'id_dpto'=>'12'],
            ['id'=>'475 ','municipio'=>'MEDIO ATRATO' ,'id_dpto'=>'12'],
            ['id'=>'476 ','municipio'=>'MEDIO BAUDO (BOCA DE PEPE)' ,'id_dpto'=>'12'],
            ['id'=>'477 ','municipio'=>'MEDIO SAN JUAN' ,'id_dpto'=>'12'],
            ['id'=>'478 ','municipio'=>'NOVITA' ,'id_dpto'=>'12'],
            ['id'=>'479 ','municipio'=>'NUQUI' ,'id_dpto'=>'12'],
            ['id'=>'480 ','municipio'=>'QUIBDO' ,'id_dpto'=>'12'],
            ['id'=>'481 ','municipio'=>'RIO IRO' ,'id_dpto'=>'12'],
            ['id'=>'482 ','municipio'=>'RIO QUITO' ,'id_dpto'=>'12'],
            ['id'=>'483 ','municipio'=>'RIOSUCIO' ,'id_dpto'=>'12'],
            ['id'=>'484 ','municipio'=>'SAN JOSE DEL PALMAR' ,'id_dpto'=>'12'],
            ['id'=>'485 ','municipio'=>'SIPI' ,'id_dpto'=>'12'],
            ['id'=>'486 ','municipio'=>'TADO' ,'id_dpto'=>'12'],
            ['id'=>'487 ','municipio'=>'UNGUIA' ,'id_dpto'=>'12'],
            ['id'=>'488 ','municipio'=>'UNIÓN PANAMERICANA' ,'id_dpto'=>'12'],
            ['id'=>'489 ','municipio'=>'AYAPEL' ,'id_dpto'=>'13'],
            ['id'=>'490 ','municipio'=>'BUENAVISTA' ,'id_dpto'=>'13'],
            ['id'=>'491 ','municipio'=>'CANALETE' ,'id_dpto'=>'13'],
            ['id'=>'492 ','municipio'=>'CERETÉ' ,'id_dpto'=>'13'],
            ['id'=>'493 ','municipio'=>'CHIMA' ,'id_dpto'=>'13'],
            ['id'=>'494 ','municipio'=>'CHINÚ' ,'id_dpto'=>'13'],
            ['id'=>'495 ','municipio'=>'CIENAGA DE ORO' ,'id_dpto'=>'13'],
            ['id'=>'496 ','municipio'=>'COTORRA' ,'id_dpto'=>'13'],
            ['id'=>'497 ','municipio'=>'LA APARTADA' ,'id_dpto'=>'13'],
            ['id'=>'498 ','municipio'=>'LORICA' ,'id_dpto'=>'13'],
            ['id'=>'499 ','municipio'=>'LOS CÓRDOBAS' ,'id_dpto'=>'13'],
            ['id'=>'500 ','municipio'=>'MOMIL' ,'id_dpto'=>'13'],
            ['id'=>'501 ','municipio'=>'MONTELÍBANO' ,'id_dpto'=>'13'],
            ['id'=>'502 ','municipio'=>'MONTERÍA' ,'id_dpto'=>'13'],
            ['id'=>'503 ','municipio'=>'MOÑITOS' ,'id_dpto'=>'13'],
            ['id'=>'504 ','municipio'=>'PLANETA RICA' ,'id_dpto'=>'13'],
            ['id'=>'505 ','municipio'=>'PUEBLO NUEVO' ,'id_dpto'=>'13'],
            ['id'=>'506 ','municipio'=>'PUERTO ESCONDIDO' ,'id_dpto'=>'13'],
            ['id'=>'507 ','municipio'=>'PUERTO LIBERTADOR' ,'id_dpto'=>'13'],
            ['id'=>'508 ','municipio'=>'PURÍSIMA' ,'id_dpto'=>'13'],
            ['id'=>'509 ','municipio'=>'SAHAGÚN' ,'id_dpto'=>'13'],
            ['id'=>'510 ','municipio'=>'SAN ANDRÉS SOTAVENTO' ,'id_dpto'=>'13'],
            ['id'=>'511 ','municipio'=>'SAN ANTERO' ,'id_dpto'=>'13'],
            ['id'=>'512 ','municipio'=>'SAN BERNARDO VIENTO' ,'id_dpto'=>'13'],
            ['id'=>'513 ','municipio'=>'SAN CARLOS' ,'id_dpto'=>'13'],
            ['id'=>'514 ','municipio'=>'SAN PELAYO' ,'id_dpto'=>'13'],
            ['id'=>'515 ','municipio'=>'TIERRALTA' ,'id_dpto'=>'13'],
            ['id'=>'516 ','municipio'=>'VALENCIA' ,'id_dpto'=>'13'],
            ['id'=>'517 ','municipio'=>'AGUA DE DIOS' ,'id_dpto'=>'14'],
            ['id'=>'518 ','municipio'=>'ALBAN' ,'id_dpto'=>'14'],
            ['id'=>'519 ','municipio'=>'ANAPOIMA' ,'id_dpto'=>'14'],
            ['id'=>'520 ','municipio'=>'ANOLAIMA' ,'id_dpto'=>'14'],
            ['id'=>'521 ','municipio'=>'ARBELAEZ' ,'id_dpto'=>'14'],
            ['id'=>'522 ','municipio'=>'BELTRÁN' ,'id_dpto'=>'14'],
            ['id'=>'523 ','municipio'=>'BITUIMA' ,'id_dpto'=>'14'],
            ['id'=>'524 ','municipio'=>'BOGOTÁ DC' ,'id_dpto'=>'14'],
            ['id'=>'525 ','municipio'=>'BOJACÁ' ,'id_dpto'=>'14'],
            ['id'=>'526 ','municipio'=>'CABRERA' ,'id_dpto'=>'14'],
            ['id'=>'527 ','municipio'=>'CACHIPAY' ,'id_dpto'=>'14'],
            ['id'=>'528 ','municipio'=>'CAJICÁ' ,'id_dpto'=>'14'],
            ['id'=>'529 ','municipio'=>'CAPARRAPÍ' ,'id_dpto'=>'14'],
            ['id'=>'530 ','municipio'=>'CAQUEZA' ,'id_dpto'=>'14'],
            ['id'=>'531 ','municipio'=>'CARMEN DE CARUPA' ,'id_dpto'=>'14'],
            ['id'=>'532 ','municipio'=>'CHAGUANÍ' ,'id_dpto'=>'14'],
            ['id'=>'533 ','municipio'=>'CHIA' ,'id_dpto'=>'14'],
            ['id'=>'534 ','municipio'=>'CHIPAQUE' ,'id_dpto'=>'14'],
            ['id'=>'535 ','municipio'=>'CHOACHÍ' ,'id_dpto'=>'14'],
            ['id'=>'536 ','municipio'=>'CHOCONTÁ' ,'id_dpto'=>'14'],
            ['id'=>'537 ','municipio'=>'COGUA' ,'id_dpto'=>'14'],
            ['id'=>'538 ','municipio'=>'COTA' ,'id_dpto'=>'14'],
            ['id'=>'539 ','municipio'=>'CUCUNUBÁ' ,'id_dpto'=>'14'],
            ['id'=>'540 ','municipio'=>'EL COLEGIO' ,'id_dpto'=>'14'],
            ['id'=>'541 ','municipio'=>'EL PEÑÓN' ,'id_dpto'=>'14'],
            ['id'=>'542 ','municipio'=>'EL ROSAL1' ,'id_dpto'=>'14'],
            ['id'=>'543 ','municipio'=>'FACATATIVA' ,'id_dpto'=>'14'],
            ['id'=>'544 ','municipio'=>'FÓMEQUE' ,'id_dpto'=>'14'],
            ['id'=>'545 ','municipio'=>'FOSCA' ,'id_dpto'=>'14'],
            ['id'=>'546 ','municipio'=>'FUNZA' ,'id_dpto'=>'14'],
            ['id'=>'547 ','municipio'=>'FÚQUENE' ,'id_dpto'=>'14'],
            ['id'=>'548 ','municipio'=>'FUSAGASUGA' ,'id_dpto'=>'14'],
            ['id'=>'549 ','municipio'=>'GACHALÁ' ,'id_dpto'=>'14'],
            ['id'=>'550 ','municipio'=>'GACHANCIPÁ' ,'id_dpto'=>'14'],
            ['id'=>'551 ','municipio'=>'GACHETA' ,'id_dpto'=>'14'],
            ['id'=>'552 ','municipio'=>'GAMA' ,'id_dpto'=>'14'],
            ['id'=>'553 ','municipio'=>'GIRARDOT' ,'id_dpto'=>'14'],
            ['id'=>'554 ','municipio'=>'GRANADA2' ,'id_dpto'=>'14'],
            ['id'=>'555 ','municipio'=>'GUACHETÁ' ,'id_dpto'=>'14'],
            ['id'=>'556 ','municipio'=>'GUADUAS' ,'id_dpto'=>'14'],
            ['id'=>'557 ','municipio'=>'GUASCA' ,'id_dpto'=>'14'],
            ['id'=>'558 ','municipio'=>'GUATAQUÍ' ,'id_dpto'=>'14'],
            ['id'=>'559 ','municipio'=>'GUATAVITA' ,'id_dpto'=>'14'],
            ['id'=>'560 ','municipio'=>'GUAYABAL DE SIQUIMA' ,'id_dpto'=>'14'],
            ['id'=>'561 ','municipio'=>'GUAYABETAL' ,'id_dpto'=>'14'],
            ['id'=>'562 ','municipio'=>'GUTIÉRREZ' ,'id_dpto'=>'14'],
            ['id'=>'563 ','municipio'=>'JERUSALÉN' ,'id_dpto'=>'14'],
            ['id'=>'564 ','municipio'=>'JUNÍN' ,'id_dpto'=>'14'],
            ['id'=>'565 ','municipio'=>'LA CALERA' ,'id_dpto'=>'14'],
            ['id'=>'566 ','municipio'=>'LA MESA' ,'id_dpto'=>'14'],
            ['id'=>'567 ','municipio'=>'LA PALMA' ,'id_dpto'=>'14'],
            ['id'=>'568 ','municipio'=>'LA PEÑA' ,'id_dpto'=>'14'],
            ['id'=>'569 ','municipio'=>'LA VEGA' ,'id_dpto'=>'14'],
            ['id'=>'570 ','municipio'=>'LENGUAZAQUE' ,'id_dpto'=>'14'],
            ['id'=>'571 ','municipio'=>'MACHETÁ' ,'id_dpto'=>'14'],
            ['id'=>'572 ','municipio'=>'MADRID' ,'id_dpto'=>'14'],
            ['id'=>'573 ','municipio'=>'MANTA' ,'id_dpto'=>'14'],
            ['id'=>'574 ','municipio'=>'MEDINA' ,'id_dpto'=>'14'],
            ['id'=>'575 ','municipio'=>'MOSQUERA' ,'id_dpto'=>'14'],
            ['id'=>'576 ','municipio'=>'NARIÑO' ,'id_dpto'=>'14'],
            ['id'=>'577 ','municipio'=>'NEMOCÓN' ,'id_dpto'=>'14'],
            ['id'=>'578 ','municipio'=>'NILO' ,'id_dpto'=>'14'],
            ['id'=>'579 ','municipio'=>'NIMAIMA' ,'id_dpto'=>'14'],
            ['id'=>'580 ','municipio'=>'NOCAIMA' ,'id_dpto'=>'14'],
            ['id'=>'581 ','municipio'=>'OSPINA PÉREZ' ,'id_dpto'=>'14'],
            ['id'=>'582 ','municipio'=>'PACHO' ,'id_dpto'=>'14'],
            ['id'=>'583 ','municipio'=>'PAIME' ,'id_dpto'=>'14'],
            ['id'=>'584 ','municipio'=>'PANDI' ,'id_dpto'=>'14'],
            ['id'=>'585 ','municipio'=>'PARATEBUENO' ,'id_dpto'=>'14'],
            ['id'=>'586 ','municipio'=>'PASCA' ,'id_dpto'=>'14'],
            ['id'=>'587 ','municipio'=>'PUERTO SALGAR' ,'id_dpto'=>'14'],
            ['id'=>'588 ','municipio'=>'PULÍ' ,'id_dpto'=>'14'],
            ['id'=>'589 ','municipio'=>'QUEBRADANEGRA' ,'id_dpto'=>'14'],
            ['id'=>'590 ','municipio'=>'QUETAME' ,'id_dpto'=>'14'],
            ['id'=>'591 ','municipio'=>'QUIPILE' ,'id_dpto'=>'14'],
            ['id'=>'592 ','municipio'=>'RAFAEL REYES' ,'id_dpto'=>'14'],
            ['id'=>'593 ','municipio'=>'RICAURTE' ,'id_dpto'=>'14'],
            ['id'=>'594 ','municipio'=>'SANANTONIO DELTEQUENDAMA' ,'id_dpto'=>'14'],
            ['id'=>'595 ','municipio'=>'SAN BERNARDO' ,'id_dpto'=>'14'],
            ['id'=>'596 ','municipio'=>'SAN CAYETANO' ,'id_dpto'=>'14'],
            ['id'=>'597 ','municipio'=>'SAN FRANCISCO' ,'id_dpto'=>'14'],
            ['id'=>'598 ','municipio'=>'SAN JUAN DE RIOSECO' ,'id_dpto'=>'14'],
            ['id'=>'599 ','municipio'=>'SASAIMA' ,'id_dpto'=>'14'],
            ['id'=>'600 ','municipio'=>'SESQUILÉ' ,'id_dpto'=>'14'],
            ['id'=>'601 ','municipio'=>'SIBATÉ' ,'id_dpto'=>'14'],
            ['id'=>'602 ','municipio'=>'SILVANIA' ,'id_dpto'=>'14'],
            ['id'=>'603 ','municipio'=>'SIMIJACA' ,'id_dpto'=>'14'],
            ['id'=>'604 ','municipio'=>'SOACHA' ,'id_dpto'=>'14'],
            ['id'=>'605 ','municipio'=>'SOPO' ,'id_dpto'=>'14'],
            ['id'=>'606 ','municipio'=>'SUBACHOQUE' ,'id_dpto'=>'14'],
            ['id'=>'607 ','municipio'=>'SUESCA' ,'id_dpto'=>'14'],
            ['id'=>'608 ','municipio'=>'SUPATÁ' ,'id_dpto'=>'14'],
            ['id'=>'609 ','municipio'=>'SUSA' ,'id_dpto'=>'14'],
            ['id'=>'610 ','municipio'=>'SUTATAUSA' ,'id_dpto'=>'14'],
            ['id'=>'611 ','municipio'=>'TABIO' ,'id_dpto'=>'14'],
            ['id'=>'612 ','municipio'=>'TAUSA' ,'id_dpto'=>'14'],
            ['id'=>'613 ','municipio'=>'TENA' ,'id_dpto'=>'14'],
            ['id'=>'614 ','municipio'=>'TENJO' ,'id_dpto'=>'14'],
            ['id'=>'615 ','municipio'=>'TIBACUY' ,'id_dpto'=>'14'],
            ['id'=>'616 ','municipio'=>'TIBIRITA' ,'id_dpto'=>'14'],
            ['id'=>'617 ','municipio'=>'TOCAIMA' ,'id_dpto'=>'14'],
            ['id'=>'618 ','municipio'=>'TOCANCIPÁ' ,'id_dpto'=>'14'],
            ['id'=>'619 ','municipio'=>'TOPAIPÍ' ,'id_dpto'=>'14'],
            ['id'=>'620 ','municipio'=>'UBALÁ' ,'id_dpto'=>'14'],
            ['id'=>'621 ','municipio'=>'UBAQUE' ,'id_dpto'=>'14'],
            ['id'=>'622 ','municipio'=>'UBATÉ' ,'id_dpto'=>'14'],
            ['id'=>'623 ','municipio'=>'UNE' ,'id_dpto'=>'14'],
            ['id'=>'624 ','municipio'=>'UTICA' ,'id_dpto'=>'14'],
            ['id'=>'625 ','municipio'=>'VERGARA' ,'id_dpto'=>'14'],
            ['id'=>'626 ','municipio'=>'VIANI' ,'id_dpto'=>'14'],
            ['id'=>'627 ','municipio'=>'VILLA GOMEZ' ,'id_dpto'=>'14'],
            ['id'=>'628 ','municipio'=>'VILLA PINZÓN' ,'id_dpto'=>'14'],
            ['id'=>'629 ','municipio'=>'VILLETA' ,'id_dpto'=>'14'],
            ['id'=>'630 ','municipio'=>'VIOTA' ,'id_dpto'=>'14'],
            ['id'=>'631 ','municipio'=>'YACOPÍ' ,'id_dpto'=>'14'],
            ['id'=>'632 ','municipio'=>'ZIPACÓN' ,'id_dpto'=>'14'],
            ['id'=>'633 ','municipio'=>'ZIPAQUIRÁ' ,'id_dpto'=>'14'],
            ['id'=>'634 ','municipio'=>'BARRANCO MINAS' ,'id_dpto'=>'15'],
            ['id'=>'635 ','municipio'=>'CACAHUAL' ,'id_dpto'=>'15'],
            ['id'=>'636 ','municipio'=>'INÍRIDA' ,'id_dpto'=>'15'],
            ['id'=>'637 ','municipio'=>'LA GUADALUPE' ,'id_dpto'=>'15'],
            ['id'=>'638 ','municipio'=>'MAPIRIPANA' ,'id_dpto'=>'15'],
            ['id'=>'639 ','municipio'=>'MORICHAL' ,'id_dpto'=>'15'],
            ['id'=>'640 ','municipio'=>'PANA PANA' ,'id_dpto'=>'15'],
            ['id'=>'641 ','municipio'=>'PUERTO COLOMBIA' ,'id_dpto'=>'15'],
            ['id'=>'642 ','municipio'=>'SAN FELIPE' ,'id_dpto'=>'15'],
            ['id'=>'643 ','municipio'=>'CALAMAR' ,'id_dpto'=>'16'],
            ['id'=>'644 ','municipio'=>'EL RETORNO' ,'id_dpto'=>'16'],
            ['id'=>'645 ','municipio'=>'MIRAFLOREZ' ,'id_dpto'=>'16'],
            ['id'=>'646 ','municipio'=>'SAN JOSÉ DEL GUAVIARE' ,'id_dpto'=>'16'],
            ['id'=>'647 ','municipio'=>'ACEVEDO' ,'id_dpto'=>'17'],
            ['id'=>'648 ','municipio'=>'AGRADO' ,'id_dpto'=>'17'],
            ['id'=>'649 ','municipio'=>'AIPE' ,'id_dpto'=>'17'],
            ['id'=>'650 ','municipio'=>'ALGECIRAS' ,'id_dpto'=>'17'],
            ['id'=>'651 ','municipio'=>'ALTAMIRA' ,'id_dpto'=>'17'],
            ['id'=>'652 ','municipio'=>'BARAYA' ,'id_dpto'=>'17'],
            ['id'=>'653 ','municipio'=>'CAMPO ALEGRE' ,'id_dpto'=>'17'],
            ['id'=>'654 ','municipio'=>'COLOMBIA' ,'id_dpto'=>'17'],
            ['id'=>'655 ','municipio'=>'ELIAS' ,'id_dpto'=>'17'],
            ['id'=>'656 ','municipio'=>'GARZÓN' ,'id_dpto'=>'17'],
            ['id'=>'657 ','municipio'=>'GIGANTE' ,'id_dpto'=>'17'],
            ['id'=>'658 ','municipio'=>'GUADALUPE' ,'id_dpto'=>'17'],
            ['id'=>'659 ','municipio'=>'HOBO' ,'id_dpto'=>'17'],
            ['id'=>'660 ','municipio'=>'IQUIRA' ,'id_dpto'=>'17'],
            ['id'=>'661 ','municipio'=>'ISNOS' ,'id_dpto'=>'17'],
            ['id'=>'662 ','municipio'=>'LA ARGENTINA' ,'id_dpto'=>'17'],
            ['id'=>'663 ','municipio'=>'LA PLATA' ,'id_dpto'=>'17'],
            ['id'=>'664 ','municipio'=>'NATAGA' ,'id_dpto'=>'17'],
            ['id'=>'665 ','municipio'=>'NEIVA' ,'id_dpto'=>'17'],
            ['id'=>'666 ','municipio'=>'OPORAPA' ,'id_dpto'=>'17'],
            ['id'=>'667 ','municipio'=>'PAICOL' ,'id_dpto'=>'17'],
            ['id'=>'668 ','municipio'=>'PALERMO' ,'id_dpto'=>'17'],
            ['id'=>'669 ','municipio'=>'PALESTINA' ,'id_dpto'=>'17'],
            ['id'=>'670 ','municipio'=>'PITAL' ,'id_dpto'=>'17'],
            ['id'=>'671 ','municipio'=>'PITALITO' ,'id_dpto'=>'17'],
            ['id'=>'672 ','municipio'=>'RIVERA' ,'id_dpto'=>'17'],
            ['id'=>'673 ','municipio'=>'SALADO BLANCO' ,'id_dpto'=>'17'],
            ['id'=>'674 ','municipio'=>'SAN AGUSTÍN' ,'id_dpto'=>'17'],
            ['id'=>'675 ','municipio'=>'SANTA MARIA' ,'id_dpto'=>'17'],
            ['id'=>'676 ','municipio'=>'SUAZA' ,'id_dpto'=>'17'],
            ['id'=>'677 ','municipio'=>'TARQUI' ,'id_dpto'=>'17'],
            ['id'=>'678 ','municipio'=>'TELLO' ,'id_dpto'=>'17'],
            ['id'=>'679 ','municipio'=>'TERUEL' ,'id_dpto'=>'17'],
            ['id'=>'680 ','municipio'=>'TESALIA' ,'id_dpto'=>'17'],
            ['id'=>'681 ','municipio'=>'TIMANA' ,'id_dpto'=>'17'],
            ['id'=>'682 ','municipio'=>'VILLAVIEJA' ,'id_dpto'=>'17'],
            ['id'=>'683 ','municipio'=>'YAGUARA' ,'id_dpto'=>'17'],
            ['id'=>'684 ','municipio'=>'ALBANIA' ,'id_dpto'=>'18'],
            ['id'=>'685 ','municipio'=>'BARRANCAS' ,'id_dpto'=>'18'],
            ['id'=>'686 ','municipio'=>'DIBULLA' ,'id_dpto'=>'18'],
            ['id'=>'687 ','municipio'=>'DISTRACCIÓN' ,'id_dpto'=>'18'],
            ['id'=>'688 ','municipio'=>'EL MOLINO' ,'id_dpto'=>'18'],
            ['id'=>'689 ','municipio'=>'FONSECA' ,'id_dpto'=>'18'],
            ['id'=>'690 ','municipio'=>'HATO NUEVO' ,'id_dpto'=>'18'],
            ['id'=>'691 ','municipio'=>'LA JAGUA DEL PILAR' ,'id_dpto'=>'18'],
            ['id'=>'692 ','municipio'=>'MAICAO' ,'id_dpto'=>'18'],
            ['id'=>'693 ','municipio'=>'MANAURE' ,'id_dpto'=>'18'],
            ['id'=>'694 ','municipio'=>'RIOHACHA' ,'id_dpto'=>'18'],
            ['id'=>'695 ','municipio'=>'SAN JUAN DEL CESAR' ,'id_dpto'=>'18'],
            ['id'=>'696 ','municipio'=>'URIBIA' ,'id_dpto'=>'18'],
            ['id'=>'697 ','municipio'=>'URUMITA' ,'id_dpto'=>'18'],
            ['id'=>'698 ','municipio'=>'VILLANUEVA' ,'id_dpto'=>'18'],
            ['id'=>'699 ','municipio'=>'ALGARROBO' ,'id_dpto'=>'19'],
            ['id'=>'700 ','municipio'=>'ARACATACA' ,'id_dpto'=>'19'],
            ['id'=>'701 ','municipio'=>'ARIGUANI' ,'id_dpto'=>'19'],
            ['id'=>'702 ','municipio'=>'CERRO SAN ANTONIO' ,'id_dpto'=>'19'],
            ['id'=>'703 ','municipio'=>'CHIVOLO' ,'id_dpto'=>'19'],
            ['id'=>'704 ','municipio'=>'CIENAGA' ,'id_dpto'=>'19'],
            ['id'=>'705 ','municipio'=>'CONCORDIA' ,'id_dpto'=>'19'],
            ['id'=>'706 ','municipio'=>'EL BANCO' ,'id_dpto'=>'19'],
            ['id'=>'707 ','municipio'=>'EL PIÑON' ,'id_dpto'=>'19'],
            ['id'=>'708 ','municipio'=>'EL RETEN' ,'id_dpto'=>'19'],
            ['id'=>'709 ','municipio'=>'FUNDACION' ,'id_dpto'=>'19'],
            ['id'=>'710 ','municipio'=>'GUAMAL' ,'id_dpto'=>'19'],
            ['id'=>'711 ','municipio'=>'NUEVA GRANADA' ,'id_dpto'=>'19'],
            ['id'=>'712 ','municipio'=>'PEDRAZA' ,'id_dpto'=>'19'],
            ['id'=>'713 ','municipio'=>'PIJIÑO DEL CARMEN' ,'id_dpto'=>'19'],
            ['id'=>'714 ','municipio'=>'PIVIJAY' ,'id_dpto'=>'19'],
            ['id'=>'715 ','municipio'=>'PLATO' ,'id_dpto'=>'19'],
            ['id'=>'716 ','municipio'=>'PUEBLO VIEJO' ,'id_dpto'=>'19'],
            ['id'=>'717 ','municipio'=>'REMOLINO' ,'id_dpto'=>'19'],
            ['id'=>'718 ','municipio'=>'SABANAS DE SAN ANGEL' ,'id_dpto'=>'19'],
            ['id'=>'719 ','municipio'=>'SALAMINA' ,'id_dpto'=>'19'],
            ['id'=>'720 ','municipio'=>'SAN SEBASTIAN DE BUENAVISTA' ,'id_dpto'=>'19'],
            ['id'=>'721 ','municipio'=>'SAN ZENON' ,'id_dpto'=>'19'],
            ['id'=>'722 ','municipio'=>'SANTA ANA' ,'id_dpto'=>'19'],
            ['id'=>'723 ','municipio'=>'SANTA BARBARA DE PINTO' ,'id_dpto'=>'19'],
            ['id'=>'724 ','municipio'=>'SANTA MARTA','id_dpto'=>'19'],
            ['id'=>'725 ','municipio'=>'SITIONUEVO','id_dpto'=>'19'],
            ['id'=>'726 ','municipio'=>'TENERIFE' ,'id_dpto'=>'19'],
            ['id'=>'727 ','municipio'=>'ZAPAYAN' ,'id_dpto'=>'19'],
            ['id'=>'728 ','municipio'=>'ZONA BANANERA' ,'id_dpto'=>'19'],
            ['id'=>'729 ','municipio'=>'ACACIAS' ,'id_dpto'=>'20'],
            ['id'=>'730 ','municipio'=>'BARRANCA DE UPIA ','id_dpto'=>'20'],
            ['id'=>'731 ','municipio'=>'CABUYARO' ,'id_dpto'=>'20'],
            ['id'=>'732 ','municipio'=>'CASTILLA LA NUEVA ' ,'id_dpto'=>'20'],
            ['id'=>'733 ','municipio'=>'CUBARRAL' ,'id_dpto'=>'20'],
            ['id'=>'734 ','municipio'=>'CUMARAL' ,'id_dpto'=>'20'],
            ['id'=>'735 ','municipio'=>'EL CALVARIO' ,'id_dpto'=>'20'],
            ['id'=>'736 ','municipio'=>'EL CASTILLO' ,'id_dpto'=>'20'],
            ['id'=>'737 ','municipio'=>'EL DORADO' ,'id_dpto'=>'20'],
            ['id'=>'738 ','municipio'=>'FUENTE DE ORO' ,'id_dpto'=>'20'],
            ['id'=>'739 ','municipio'=>'GRANADA' ,'id_dpto'=>'20'],
            ['id'=>'740 ','municipio'=>'GUAMAL' ,'id_dpto'=>'20'],
            ['id'=>'741 ','municipio'=>'LA MACARENA' ,'id_dpto'=>'20'],
            ['id'=>'742 ','municipio'=>'LA URIBE' ,'id_dpto'=>'20'],
            ['id'=>'743 ','municipio'=>'LEJANÍAS' ,'id_dpto'=>'20'],
            ['id'=>'744 ','municipio'=>'MAPIRIPÁN' ,'id_dpto'=>'20'],
            ['id'=>'745 ','municipio'=>'MESETAS' ,'id_dpto'=>'20'],
            ['id'=>'746 ','municipio'=>'PUERTO CONCORDIA','id_dpto'=>'20'],
            ['id'=>'747 ','municipio'=>'PUERTO GAITÁN' ,'id_dpto'=>'20'],
            ['id'=>'748 ','municipio'=>'PUERTO LLERAS' ,'id_dpto'=>'20'],
            ['id'=>'749 ','municipio'=>'PUERTO LÓPEZ' ,'id_dpto'=>'20'],
            ['id'=>'750 ','municipio'=>'PUERTO RICO' ,'id_dpto'=>'20'],
            ['id'=>'751 ','municipio'=>'RESTREPO' ,'id_dpto'=>'20'],
            ['id'=>'752 ','municipio'=>'SANJUAN DE ARAMA ','id_dpto'=>'20'],
            ['id'=>'753 ','municipio'=>'SAN CARLOS GUAROA ','id_dpto'=>'20'],
            ['id'=>'754 ','municipio'=>'SAN JUANITO' ,'id_dpto'=>'20'],
            ['id'=>'755 ','municipio'=>'SAN MARTÍN' ,'id_dpto'=>'20'],
            ['id'=>'756 ','municipio'=>'VILLAVICENCIO' ,'id_dpto'=>'20'],
            ['id'=>'757 ','municipio'=>'VISTA HERMOSA' ,'id_dpto'=>'20'],
            ['id'=>'758 ','municipio'=>'ALBAN' ,'id_dpto'=>'21'],
            ['id'=>'759 ','municipio'=>'ALDAÑA' ,'id_dpto'=>'21'],
            ['id'=>'760 ','municipio'=>'ANCUYA' ,'id_dpto'=>'21'],
            ['id'=>'761 ','municipio'=>'ARBOLEDA' ,'id_dpto'=>'21'],
            ['id'=>'762 ','municipio'=>'BARBACOAS' ,'id_dpto'=>'21'],
            ['id'=>'763 ','municipio'=>'BELEN' ,'id_dpto'=>'21'],
            ['id'=>'764 ','municipio'=>'BUESACO' ,'id_dpto'=>'21'],
            ['id'=>'765 ','municipio'=>'CHACHAGUI' ,'id_dpto'=>'21'],
            ['id'=>'766 ','municipio'=>'COLON (GENOVA)' ,'id_dpto'=>'21'],
            ['id'=>'767 ','municipio'=>'CONSACA' ,'id_dpto'=>'21'],
            ['id'=>'768 ','municipio'=>'CONTADERO' ,'id_dpto'=>'21'],
            ['id'=>'769 ','municipio'=>'CORDOBA' ,'id_dpto'=>'21'],
            ['id'=>'770 ','municipio'=>'CUASPUD' ,'id_dpto'=>'21'],
            ['id'=>'771 ','municipio'=>'CUMBAL' ,'id_dpto'=>'21'],
            ['id'=>'772 ','municipio'=>'CUMBITARA' ,'id_dpto'=>'21'],
            ['id'=>'773 ','municipio'=>'EL CHARCO' ,'id_dpto'=>'21'],
            ['id'=>'774 ','municipio'=>'EL PEÑOL' ,'id_dpto'=>'21'],
            ['id'=>'775 ','municipio'=>'EL ROSARIO' ,'id_dpto'=>'21'],
            ['id'=>'776 ','municipio'=>'EL TABLÓN' ,'id_dpto'=>'21'],
            ['id'=>'777 ','municipio'=>'EL TAMBO' ,'id_dpto'=>'21'],
            ['id'=>'778 ','municipio'=>'FUNES' ,'id_dpto'=>'21'],
            ['id'=>'779 ','municipio'=>'GUACHUCAL' ,'id_dpto'=>'21'],
            ['id'=>'780 ','municipio'=>'GUAITARILLA' ,'id_dpto'=>'21'],
            ['id'=>'781 ','municipio'=>'GUALMATAN' ,'id_dpto'=>'21'],
            ['id'=>'782 ','municipio'=>'ILES' ,'id_dpto'=>'21'],
            ['id'=>'783 ','municipio'=>'IMUES' ,'id_dpto'=>'21'],
            ['id'=>'784 ','municipio'=>'IPIALES' ,'id_dpto'=>'21'],
            ['id'=>'785 ','municipio'=>'LA CRUZ' ,'id_dpto'=>'21'],
            ['id'=>'786 ','municipio'=>'LA FLORIDA' ,'id_dpto'=>'21'],
            ['id'=>'787 ','municipio'=>'LA LLANADA' ,'id_dpto'=>'21'],
            ['id'=>'788 ','municipio'=>'LA TOLA' ,'id_dpto'=>'21'],
            ['id'=>'789 ','municipio'=>'LA UNION' ,'id_dpto'=>'21'],
            ['id'=>'790 ','municipio'=>'LEIVA' ,'id_dpto'=>'21'],
            ['id'=>'791 ','municipio'=>'LINARES' ,'id_dpto'=>'21'],
            ['id'=>'792 ','municipio'=>'LOS ANDES' ,'id_dpto'=>'21'],
            ['id'=>'793 ','municipio'=>'MAGUI' ,'id_dpto'=>'21'],
            ['id'=>'794 ','municipio'=>'MALLAMA' ,'id_dpto'=>'21'],
            ['id'=>'795 ','municipio'=>'MOSQUEZA' ,'id_dpto'=>'21'],
            ['id'=>'796 ','municipio'=>'NARIÑO' ,'id_dpto'=>'21'],
            ['id'=>'797 ','municipio'=>'OLAYA HERRERA' ,'id_dpto'=>'21'],
            ['id'=>'798 ','municipio'=>'OSPINA' ,'id_dpto'=>'21'],
            ['id'=>'799 ','municipio'=>'PASTO' ,'id_dpto'=>'21'],
            ['id'=>'800 ','municipio'=>'PIZARRO' ,'id_dpto'=>'21'],
            ['id'=>'801 ','municipio'=>'POLICARPA' ,'id_dpto'=>'21'],
            ['id'=>'802 ','municipio'=>'POTOSI' ,'id_dpto'=>'21'],
            ['id'=>'803 ','municipio'=>'PROVIDENCIA' ,'id_dpto'=>'21'],
            ['id'=>'804 ','municipio'=>'PUERRES' ,'id_dpto'=>'21'],
            ['id'=>'805 ','municipio'=>'PUPIALES' ,'id_dpto'=>'21'],
            ['id'=>'806 ','municipio'=>'RICAURTE' ,'id_dpto'=>'21'],
            ['id'=>'807 ','municipio'=>'ROBERTO PAYAN' ,'id_dpto'=>'21'],
            ['id'=>'808 ','municipio'=>'SAMANIEGO' ,'id_dpto'=>'21'],
            ['id'=>'809 ','municipio'=>'SAN BERNARDO' ,'id_dpto'=>'21'],
            ['id'=>'810 ','municipio'=>'SAN LORENZO' ,'id_dpto'=>'21'],
            ['id'=>'811 ','municipio'=>'SAN PABLO' ,'id_dpto'=>'21'],
            ['id'=>'812 ','municipio'=>'SAN PEDRO DE CARTAGO' ,'id_dpto'=>'21'],
            ['id'=>'813 ','municipio'=>'SANDONA' ,'id_dpto'=>'21'],
            ['id'=>'814 ','municipio'=>'SANTA BARBARA' ,'id_dpto'=>'21'],
            ['id'=>'815 ','municipio'=>'SANTACRUZ' ,'id_dpto'=>'21'],
            ['id'=>'816 ','municipio'=>'SAPUYES' ,'id_dpto'=>'21'],
            ['id'=>'817 ','municipio'=>'TAMINANGO' ,'id_dpto'=>'21'],
            ['id'=>'818 ','municipio'=>'TANGUA' ,'id_dpto'=>'21'],
            ['id'=>'819 ','municipio'=>'TUMACO' ,'id_dpto'=>'21'],
            ['id'=>'820 ','municipio'=>'TUQUERRES' ,'id_dpto'=>'21'],
            ['id'=>'821 ','municipio'=>'YACUANQUER' ,'id_dpto'=>'21'],
            ['id'=>'822 ','municipio'=>'ABREGO' ,'id_dpto'=>'22'],
            ['id'=>'823 ','municipio'=>'ARBOLEDAS' ,'id_dpto'=>'22'],
            ['id'=>'824 ','municipio'=>'BOCHALEMA' ,'id_dpto'=>'22'],
            ['id'=>'825 ','municipio'=>'BUCARASICA' ,'id_dpto'=>'22'],
            ['id'=>'826 ','municipio'=>'CÁCHIRA' ,'id_dpto'=>'22'],
            ['id'=>'827 ','municipio'=>'CÁCOTA' ,'id_dpto'=>'22'],
            ['id'=>'828 ','municipio'=>'CHINÁCOTA' ,'id_dpto'=>'22'],
            ['id'=>'829 ','municipio'=>'CHITAGÁ' ,'id_dpto'=>'22'],
            ['id'=>'830 ','municipio'=>'CONVENCIÓN' ,'id_dpto'=>'22'],
            ['id'=>'831 ','municipio'=>'CÚCUTA' ,'id_dpto'=>'22'],
            ['id'=>'832 ','municipio'=>'CUCUTILLA' ,'id_dpto'=>'22'],
            ['id'=>'833 ','municipio'=>'DURANIA' ,'id_dpto'=>'22'],
            ['id'=>'834 ','municipio'=>'EL CARMEN' ,'id_dpto'=>'22'],
            ['id'=>'835 ','municipio'=>'EL TARRA' ,'id_dpto'=>'22'],
            ['id'=>'836 ','municipio'=>'EL ZULIA' ,'id_dpto'=>'22'],
            ['id'=>'837 ','municipio'=>'GRAMALOTE' ,'id_dpto'=>'22'],
            ['id'=>'838 ','municipio'=>'HACARI' ,'id_dpto'=>'22'],
            ['id'=>'839 ','municipio'=>'HERRÁN' ,'id_dpto'=>'22'],
            ['id'=>'840 ','municipio'=>'LA ESPERANZA' ,'id_dpto'=>'22'],
            ['id'=>'841 ','municipio'=>'LA PLAYA' ,'id_dpto'=>'22'],
            ['id'=>'842 ','municipio'=>'LABATECA' ,'id_dpto'=>'22'],
            ['id'=>'843 ','municipio'=>'LOS PATIOS' ,'id_dpto'=>'22'],
            ['id'=>'844 ','municipio'=>'LOURDES' ,'id_dpto'=>'22'],
            ['id'=>'845 ','municipio'=>'MUTISCUA' ,'id_dpto'=>'22'],
            ['id'=>'846 ','municipio'=>'OCAÑA' ,'id_dpto'=>'22'],
            ['id'=>'847 ','municipio'=>'PAMPLONA' ,'id_dpto'=>'22'],
            ['id'=>'848 ','municipio'=>'PAMPLONITA' ,'id_dpto'=>'22'],
            ['id'=>'849 ','municipio'=>'PUERTO SANTANDER' ,'id_dpto'=>'22'],
            ['id'=>'850 ','municipio'=>'RAGONVALIA' ,'id_dpto'=>'22'],
            ['id'=>'851 ','municipio'=>'SALAZAR' ,'id_dpto'=>'22'],
            ['id'=>'852 ','municipio'=>'SAN CALIXTO' ,'id_dpto'=>'22'],
            ['id'=>'853 ','municipio'=>'SAN CAYETANO' ,'id_dpto'=>'22'],
            ['id'=>'854 ','municipio'=>'SANTIAGO' ,'id_dpto'=>'22'],
            ['id'=>'855 ','municipio'=>'SARDINATA' ,'id_dpto'=>'22'],
            ['id'=>'856 ','municipio'=>'SILOS' ,'id_dpto'=>'22'],
            ['id'=>'857 ','municipio'=>'TEORAMA' ,'id_dpto'=>'22'],
            ['id'=>'858 ','municipio'=>'TIBÚ' ,'id_dpto'=>'22'],
            ['id'=>'859 ','municipio'=>'TOLEDO' ,'id_dpto'=>'22'],
            ['id'=>'860 ','municipio'=>'VILLA CARO' ,'id_dpto'=>'22'],
            ['id'=>'861 ','municipio'=>'VILLA DEL ROSARIO' ,'id_dpto'=>'22'],
            ['id'=>'862 ','municipio'=>'COLÓN' ,'id_dpto'=>'23'],
            ['id'=>'863 ','municipio'=>'MOCOA' ,'id_dpto'=>'23'],
            ['id'=>'864 ','municipio'=>'ORITO' ,'id_dpto'=>'23'],
            ['id'=>'865 ','municipio'=>'PUERTO ASÍS' ,'id_dpto'=>'23'],
            ['id'=>'866 ','municipio'=>'PUERTO CAYCEDO' ,'id_dpto'=>'23'],
            ['id'=>'867 ','municipio'=>'PUERTO GUZMÁN' ,'id_dpto'=>'23'],
            ['id'=>'868 ','municipio'=>'PUERTO LEGUÍZAMO' ,'id_dpto'=>'23'],
            ['id'=>'869 ','municipio'=>'SAN FRANCISCO' ,'id_dpto'=>'23'],
            ['id'=>'870 ','municipio'=>'SAN MIGUEL' ,'id_dpto'=>'23'],
            ['id'=>'871 ','municipio'=>'SANTIAGO' ,'id_dpto'=>'23'],
            ['id'=>'872 ','municipio'=>'SIBUNDOY' ,'id_dpto'=>'23'],
            ['id'=>'873 ','municipio'=>'VALLE DEL GUAMUEZ' ,'id_dpto'=>'23'],
            ['id'=>'874 ','municipio'=>'VILLAGARZÓN' ,'id_dpto'=>'23'],
            ['id'=>'875 ','municipio'=>'ARMENIA' ,'id_dpto'=>'24'],
            ['id'=>'876 ','municipio'=>'BUENAVISTA' ,'id_dpto'=>'24'],
            ['id'=>'877 ','municipio'=>'CALARCÁ' ,'id_dpto'=>'24'],
            ['id'=>'878 ','municipio'=>'CIRCASIA' ,'id_dpto'=>'24'],
            ['id'=>'879 ','municipio'=>'CÓRDOBA' ,'id_dpto'=>'24'],
            ['id'=>'880 ','municipio'=>'FILANDIA' ,'id_dpto'=>'24'],
            ['id'=>'881 ','municipio'=>'GÉNOVA' ,'id_dpto'=>'24'],
            ['id'=>'882 ','municipio'=>'LA TEBAIDA' ,'id_dpto'=>'24'],
            ['id'=>'883 ','municipio'=>'MONTENEGRO' ,'id_dpto'=>'24'],
            ['id'=>'884 ','municipio'=>'PIJAO' ,'id_dpto'=>'24'],
            ['id'=>'885 ','municipio'=>'QUIMBAYA' ,'id_dpto'=>'24'],
            ['id'=>'886 ','municipio'=>'SALENTO' ,'id_dpto'=>'24'],
            ['id'=>'887 ','municipio'=>'APIA' ,'id_dpto'=>'25'],
            ['id'=>'888 ','municipio'=>'BALBOA' ,'id_dpto'=>'25'],
            ['id'=>'889 ','municipio'=>'BELÉN DE UMBRÍA' ,'id_dpto'=>'25'],
            ['id'=>'890 ','municipio'=>'DOS QUEBRADAS' ,'id_dpto'=>'25'],
            ['id'=>'891 ','municipio'=>'GUATICA' ,'id_dpto'=>'25'],
            ['id'=>'892 ','municipio'=>'LA CELIA' ,'id_dpto'=>'25'],
            ['id'=>'893 ','municipio'=>'LA VIRGINIA' ,'id_dpto'=>'25'],
            ['id'=>'894 ','municipio'=>'MARSELLA' ,'id_dpto'=>'25'],
            ['id'=>'895 ','municipio'=>'MISTRATO' ,'id_dpto'=>'25'],
            ['id'=>'896 ','municipio'=>'PEREIRA' ,'id_dpto'=>'25'],
            ['id'=>'897 ','municipio'=>'PUEBLO RICO' ,'id_dpto'=>'25'],
            ['id'=>'898 ','municipio'=>'QUINCHÍA' ,'id_dpto'=>'25'],
            ['id'=>'899 ','municipio'=>'SANTA ROSA DE CABAL' ,'id_dpto'=>'25'],
            ['id'=>'900 ','municipio'=>'SANTUARIO' ,'id_dpto'=>'25'],
            ['id'=>'901 ','municipio'=>'PROVIDENCIA' ,'id_dpto'=>'26'],
            ['id'=>'902 ','municipio'=>'SAN ANDRES' ,'id_dpto'=>'26'],
            ['id'=>'903 ','municipio'=>'SANTA CATALINA' ,'id_dpto'=>'26'],
            ['id'=>'904 ','municipio'=>'AGUADA' ,'id_dpto'=>'27'],
            ['id'=>'905 ','municipio'=>'ALBANIA' ,'id_dpto'=>'27'],
            ['id'=>'906 ','municipio'=>'ARATOCA' ,'id_dpto'=>'27'],
            ['id'=>'907 ','municipio'=>'BARBOSA' ,'id_dpto'=>'27'],
            ['id'=>'908 ','municipio'=>'BARICHARA' ,'id_dpto'=>'27'],
            ['id'=>'909 ','municipio'=>'BARRANCABERMEJA' ,'id_dpto'=>'27'],
            ['id'=>'910 ','municipio'=>'BETULIA' ,'id_dpto'=>'27'],
            ['id'=>'911 ','municipio'=>'BOLÍVAR' ,'id_dpto'=>'27'],
            ['id'=>'912 ','municipio'=>'BUCARAMANGA' ,'id_dpto'=>'27'],
            ['id'=>'913 ','municipio'=>'CABRERA' ,'id_dpto'=>'27'],
            ['id'=>'914 ','municipio'=>'CALIFORNIA' ,'id_dpto'=>'27'],
            ['id'=>'915 ','municipio'=>'CAPITANEJO' ,'id_dpto'=>'27'],
            ['id'=>'916 ','municipio'=>'CARCASI' ,'id_dpto'=>'27'],
            ['id'=>'917 ','municipio'=>'CEPITA' ,'id_dpto'=>'27'],
            ['id'=>'918 ','municipio'=>'CERRITO' ,'id_dpto'=>'27'],
            ['id'=>'919 ','municipio'=>'CHARALÁ' ,'id_dpto'=>'27'],
            ['id'=>'920 ','municipio'=>'CHARTA' ,'id_dpto'=>'27'],
            ['id'=>'921 ','municipio'=>'CHIMA' ,'id_dpto'=>'27'],
            ['id'=>'922 ','municipio'=>'CHIPATÁ' ,'id_dpto'=>'27'],
            ['id'=>'923 ','municipio'=>'CIMITARRA' ,'id_dpto'=>'27'],
            ['id'=>'924 ','municipio'=>'CONCEPCIÓN' ,'id_dpto'=>'27'],
            ['id'=>'925 ','municipio'=>'CONFINES' ,'id_dpto'=>'27'],
            ['id'=>'926 ','municipio'=>'CONTRATACIÓN' ,'id_dpto'=>'27'],
            ['id'=>'927 ','municipio'=>'COROMORO' ,'id_dpto'=>'27'],
            ['id'=>'928 ','municipio'=>'CURITÍ' ,'id_dpto'=>'27'],
            ['id'=>'929 ','municipio'=>'EL CARMEN' ,'id_dpto'=>'27'],
            ['id'=>'930 ','municipio'=>'EL GUACAMAYO' ,'id_dpto'=>'27'],
            ['id'=>'931 ','municipio'=>'EL PEÑÓN' ,'id_dpto'=>'27'],
            ['id'=>'932 ','municipio'=>'EL PLAYÓN' ,'id_dpto'=>'27'],
            ['id'=>'933 ','municipio'=>'ENCINO' ,'id_dpto'=>'27'],
            ['id'=>'934 ','municipio'=>'ENCISO' ,'id_dpto'=>'27'],
            ['id'=>'935 ','municipio'=>'FLORIÁN' ,'id_dpto'=>'27'],
            ['id'=>'936 ','municipio'=>'FLORIDABLANCA' ,'id_dpto'=>'27'],
            ['id'=>'937 ','municipio'=>'GALÁN' ,'id_dpto'=>'27'],
            ['id'=>'938 ','municipio'=>'GAMBITA' ,'id_dpto'=>'27'],
            ['id'=>'939 ','municipio'=>'GIRÓN' ,'id_dpto'=>'27'],
            ['id'=>'940 ','municipio'=>'GUACA' ,'id_dpto'=>'27'],
            ['id'=>'941 ','municipio'=>'GUADALUPE' ,'id_dpto'=>'27'],
            ['id'=>'942 ','municipio'=>'GUAPOTA' ,'id_dpto'=>'27'],
            ['id'=>'943 ','municipio'=>'GUAVATÁ' ,'id_dpto'=>'27'],
            ['id'=>'944 ','municipio'=>'GUEPSA' ,'id_dpto'=>'27'],
            ['id'=>'945 ','municipio'=>'HATO' ,'id_dpto'=>'27'],
            ['id'=>'946 ','municipio'=>'JESÚS MARIA' ,'id_dpto'=>'27'],
            ['id'=>'947 ','municipio'=>'JORDÁN' ,'id_dpto'=>'27'],
            ['id'=>'948 ','municipio'=>'LA BELLEZA' ,'id_dpto'=>'27'],
            ['id'=>'949 ','municipio'=>'LA PAZ' ,'id_dpto'=>'27'],
            ['id'=>'950 ','municipio'=>'LANDAZURI' ,'id_dpto'=>'27'],
            ['id'=>'951 ','municipio'=>'LEBRIJA' ,'id_dpto'=>'27'],
            ['id'=>'952 ','municipio'=>'LOS SANTOS' ,'id_dpto'=>'27'],
            ['id'=>'953 ','municipio'=>'MACARAVITA' ,'id_dpto'=>'27'],
            ['id'=>'954 ','municipio'=>'MÁLAGA' ,'id_dpto'=>'27'],
            ['id'=>'955 ','municipio'=>'MATANZA' ,'id_dpto'=>'27'],
            ['id'=>'956 ','municipio'=>'MOGOTES' ,'id_dpto'=>'27'],
            ['id'=>'957 ','municipio'=>'MOLAGAVITA' ,'id_dpto'=>'27'],
            ['id'=>'958 ','municipio'=>'OCAMONTE' ,'id_dpto'=>'27'],
            ['id'=>'959 ','municipio'=>'OIBA' ,'id_dpto'=>'27'],
            ['id'=>'960 ','municipio'=>'ONZAGA' ,'id_dpto'=>'27'],
            ['id'=>'961 ','municipio'=>'PALMAR' ,'id_dpto'=>'27'],
            ['id'=>'962 ','municipio'=>'PALMAS DEL SOCORRO' ,'id_dpto'=>'27'],
            ['id'=>'963 ','municipio'=>'PÁRAMO' ,'id_dpto'=>'27'],
            ['id'=>'964 ','municipio'=>'PIEDECUESTA' ,'id_dpto'=>'27'],
            ['id'=>'965 ','municipio'=>'PINCHOTE' ,'id_dpto'=>'27'],
            ['id'=>'966 ','municipio'=>'PUENTE NACIONAL' ,'id_dpto'=>'27'],
            ['id'=>'967 ','municipio'=>'PUERTO PARRA' ,'id_dpto'=>'27'],
            ['id'=>'968 ','municipio'=>'PUERTO WILCHES' ,'id_dpto'=>'27'],
            ['id'=>'969 ','municipio'=>'RIONEGRO' ,'id_dpto'=>'27'],
            ['id'=>'970 ','municipio'=>'SABANA DE TORRES' ,'id_dpto'=>'27'],
            ['id'=>'971 ','municipio'=>'SAN ANDRÉS' ,'id_dpto'=>'27'],
            ['id'=>'972 ','municipio'=>'SAN BENITO' ,'id_dpto'=>'27'],
            ['id'=>'973 ','municipio'=>'SAN GIL' ,'id_dpto'=>'27'],
            ['id'=>'974 ','municipio'=>'SAN JOAQUÍN' ,'id_dpto'=>'27'],
            ['id'=>'975 ','municipio'=>'SAN JOSÉ DE MIRANDA' ,'id_dpto'=>'27'],
            ['id'=>'976 ','municipio'=>'SAN MIGUEL' ,'id_dpto'=>'27'],
            ['id'=>'977 ','municipio'=>'SAN VICENTE DE CHUCURÍ' ,'id_dpto'=>'27'],
            ['id'=>'978 ','municipio'=>'SANTA BÁRBARA' ,'id_dpto'=>'27'],
            ['id'=>'979 ','municipio'=>'SANTA HELENA' ,'id_dpto'=>'27'],
            ['id'=>'980 ','municipio'=>'SIMACOTA' ,'id_dpto'=>'27'],
            ['id'=>'981 ','municipio'=>'SOCORRO' ,'id_dpto'=>'27'],
            ['id'=>'982 ','municipio'=>'SUAITA' ,'id_dpto'=>'27'],
            ['id'=>'983 ','municipio'=>'SUCRE' ,'id_dpto'=>'27'],
            ['id'=>'984 ','municipio'=>'SURATA' ,'id_dpto'=>'27'],
            ['id'=>'985 ','municipio'=>'TONA' ,'id_dpto'=>'27'],
            ['id'=>'986 ','municipio'=>'VALLE SAN JOSÉ' ,'id_dpto'=>'27'],
            ['id'=>'987 ','municipio'=>'VÉLEZ' ,'id_dpto'=>'27'],
            ['id'=>'988 ','municipio'=>'VETAS' ,'id_dpto'=>'27'],
            ['id'=>'989 ','municipio'=>'VILLANUEVA' ,'id_dpto'=>'27'],
            ['id'=>'990 ','municipio'=>'ZAPATOCA' ,'id_dpto'=>'27'],
            ['id'=>'991 ','municipio'=>'BUENAVISTA' ,'id_dpto'=>'28'],
            ['id'=>'992 ','municipio'=>'CAIMITO' ,'id_dpto'=>'28'],
            ['id'=>'993 ','municipio'=>'CHALÁN' ,'id_dpto'=>'28'],
            ['id'=>'994 ','municipio'=>'COLOSO' ,'id_dpto'=>'28'],
            ['id'=>'995 ','municipio'=>'COROZAL' ,'id_dpto'=>'28'],
            ['id'=>'996 ','municipio'=>'EL ROBLE' ,'id_dpto'=>'28'],
            ['id'=>'997 ','municipio'=>'GALERAS' ,'id_dpto'=>'28'],
            ['id'=>'998 ','municipio'=>'GUARANDA' ,'id_dpto'=>'28'],
            ['id'=>'999 ','municipio'=>'LA UNIÓ' ,'id_dpto'=>'28'],
            ['id'=>'1000','municipio'=>'LOS PALMITO' ,'id_dpto'=>'28'],
            ['id'=>'1001','municipio'=>'MAJAGUA' ,'id_dpto'=>'28'],
            ['id'=>'1002','municipio'=>'MORRO' ,'id_dpto'=>'28'],
            ['id'=>'1003','municipio'=>'OVEJA' ,'id_dpto'=>'28'],
            ['id'=>'1004','municipio'=>'PALMIT' ,'id_dpto'=>'28'],
            ['id'=>'1005','municipio'=>'SAMPUE' ,'id_dpto'=>'28'],
            ['id'=>'1006','municipio'=>'SAN BENITO ABA' ,'id_dpto'=>'28'],
            ['id'=>'1007','municipio'=>'SAN JUAN DE BETULI' ,'id_dpto'=>'28'],
            ['id'=>'1008','municipio'=>'SAN MARCO' ,'id_dpto'=>'28'],
            ['id'=>'1009','municipio'=>'SAN ONOFR' ,'id_dpto'=>'28'],
            ['id'=>'1010','municipio'=>'SAN PEDR' ,'id_dpto'=>'28'],
            ['id'=>'1011','municipio'=>'SINC' ,'id_dpto'=>'28'],
            ['id'=>'1012','municipio'=>'SINCELEJ' ,'id_dpto'=>'28'],
            ['id'=>'1013','municipio'=>'SUCR' ,'id_dpto'=>'28'],
            ['id'=>'1014','municipio'=>'TOL' ,'id_dpto'=>'28'],
            ['id'=>'1015','municipio'=>'TOLUVIEJ' ,'id_dpto'=>'28'],
            ['id'=>'1016','municipio'=>'ALPUJARR' ,'id_dpto'=>'29'],
            ['id'=>'1017','municipio'=>'ALVARAD' ,'id_dpto'=>'29'],
            ['id'=>'1018','municipio'=>'AMBALEM' ,'id_dpto'=>'29'],
            ['id'=>'1019','municipio'=>'ANZOATEGU' ,'id_dpto'=>'29'],
            ['id'=>'1020','municipio'=>'ARMERO (GUAYABAL' ,'id_dpto'=>'29'],
            ['id'=>'1021','municipio'=>'ATAC' ,'id_dpto'=>'29'],
            ['id'=>'1022','municipio'=>'CAJAMARC' ,'id_dpto'=>'29'],
            ['id'=>'1023','municipio'=>'CARMEN DE APICAL' ,'id_dpto'=>'29'],
            ['id'=>'1024','municipio'=>'CASABIANC' ,'id_dpto'=>'29'],
            ['id'=>'1025','municipio'=>'CHAPARRA' ,'id_dpto'=>'29'],
            ['id'=>'1026','municipio'=>'COELL' ,'id_dpto'=>'29'],
            ['id'=>'1027','municipio'=>'COYAIM' ,'id_dpto'=>'29'],
            ['id'=>'1028','municipio'=>'CUNDA' ,'id_dpto'=>'29'],
            ['id'=>'1029','municipio'=>'DOLORE' ,'id_dpto'=>'29'],
            ['id'=>'1030','municipio'=>'ESPINA' ,'id_dpto'=>'29'],
            ['id'=>'1031','municipio'=>'FALÁ' ,'id_dpto'=>'29'],
            ['id'=>'1032','municipio'=>'FLANDE' ,'id_dpto'=>'29'],
            ['id'=>'1033','municipio'=>'FRESN' ,'id_dpto'=>'29'],
            ['id'=>'1034','municipio'=>'GUAM' ,'id_dpto'=>'29'],
            ['id'=>'1035','municipio'=>'HERVE' ,'id_dpto'=>'29'],
            ['id'=>'1036','municipio'=>'HOND' ,'id_dpto'=>'29'],
            ['id'=>'1037','municipio'=>'IBAGU' ,'id_dpto'=>'29'],
            ['id'=>'1038','municipio'=>'ICONONZ' ,'id_dpto'=>'29'],
            ['id'=>'1039','municipio'=>'LÉRID' ,'id_dpto'=>'29'],
            ['id'=>'1040','municipio'=>'LÍBAN' ,'id_dpto'=>'29'],
            ['id'=>'1041','municipio'=>'MARIQUIT' ,'id_dpto'=>'29'],
            ['id'=>'1042','municipio'=>'MELGA' ,'id_dpto'=>'29'],
            ['id'=>'1043','municipio'=>'MURILL' ,'id_dpto'=>'29'],
            ['id'=>'1044','municipio'=>'NATAGAIM' ,'id_dpto'=>'29'],
            ['id'=>'1045','municipio'=>'ORTEG' ,'id_dpto'=>'29'],
            ['id'=>'1046','municipio'=>'PALOCABILD' ,'id_dpto'=>'29'],
            ['id'=>'1047','municipio'=>'PIEDRAS PLANADA' ,'id_dpto'=>'29'],
            ['id'=>'1048','municipio'=>'PRAD' ,'id_dpto'=>'29'],
            ['id'=>'1049','municipio'=>'PURIFICACIÓ' ,'id_dpto'=>'29'],
            ['id'=>'1050','municipio'=>'RIOBLANC' ,'id_dpto'=>'29'],
            ['id'=>'1051','municipio'=>'RONCESVALLE' ,'id_dpto'=>'29'],
            ['id'=>'1052','municipio'=>'ROVIR' ,'id_dpto'=>'29'],
            ['id'=>'1053','municipio'=>'SALDAÑ' ,'id_dpto'=>'29'],
            ['id'=>'1054','municipio'=>'SAN ANTONI' ,'id_dpto'=>'29'],
            ['id'=>'1055','municipio'=>'SAN LUI' ,'id_dpto'=>'29'],
            ['id'=>'1056','municipio'=>'SANTA ISABE' ,'id_dpto'=>'29'],
            ['id'=>'1057','municipio'=>'SUÁRE' ,'id_dpto'=>'29'],
            ['id'=>'1058','municipio'=>'VALLE DE SAN JUA' ,'id_dpto'=>'29'],
            ['id'=>'1059','municipio'=>'VENADILL' ,'id_dpto'=>'29'],
            ['id'=>'1060','municipio'=>'VILLAHERMOS' ,'id_dpto'=>'29'],
            ['id'=>'1061','municipio'=>'VILLARRIC' ,'id_dpto'=>'29'],
            ['id'=>'1062','municipio'=>'ALCAL' ,'id_dpto'=>'30'],
            ['id'=>'1063','municipio'=>'ANDALUCÍ' ,'id_dpto'=>'30'],
            ['id'=>'1064','municipio'=>'ANSERMA NUEV' ,'id_dpto'=>'30'],
            ['id'=>'1065','municipio'=>'ARGELI' ,'id_dpto'=>'30'],
            ['id'=>'1066','municipio'=>'BOLÍVA' ,'id_dpto'=>'30'],
            ['id'=>'1067','municipio'=>'BUENAVENTUR' ,'id_dpto'=>'30'],
            ['id'=>'1068','municipio'=>'BUG' ,'id_dpto'=>'30'],
            ['id'=>'1069','municipio'=>'BUGALAGRAND' ,'id_dpto'=>'30'],
            ['id'=>'1070','municipio'=>'CAICEDONI' ,'id_dpto'=>'30'],
            ['id'=>'1071','municipio'=>'CAL' ,'id_dpto'=>'30'],
            ['id'=>'1072','municipio'=>'CALIMA (DARIEN' ,'id_dpto'=>'30'],
            ['id'=>'1073','municipio'=>'CANDELARI' ,'id_dpto'=>'30'],
            ['id'=>'1074','municipio'=>'CARTAG' ,'id_dpto'=>'30'],
            ['id'=>'1075','municipio'=>'DAGU' ,'id_dpto'=>'30'],
            ['id'=>'1076','municipio'=>'EL AGUIL' ,'id_dpto'=>'30'],
            ['id'=>'1077','municipio'=>'EL CAIR' ,'id_dpto'=>'30'],
            ['id'=>'1078','municipio'=>'EL CERRIT' ,'id_dpto'=>'30'],
            ['id'=>'1079','municipio'=>'EL DOVI' ,'id_dpto'=>'30'],
            ['id'=>'1080','municipio'=>'FLORID' ,'id_dpto'=>'30'],
            ['id'=>'1081','municipio'=>'GINEBRA GUACAR' ,'id_dpto'=>'30'],
            ['id'=>'1082','municipio'=>'JAMUND' ,'id_dpto'=>'30'],
            ['id'=>'1083','municipio'=>'LA CUMBR' ,'id_dpto'=>'30'],
            ['id'=>'1084','municipio'=>'LA UNIÓ' ,'id_dpto'=>'30'],
            ['id'=>'1085','municipio'=>'LA VICTORI' ,'id_dpto'=>'30'],
            ['id'=>'1086','municipio'=>'OBAND' ,'id_dpto'=>'30'],
            ['id'=>'1087','municipio'=>'PALMIR' ,'id_dpto'=>'30'],
            ['id'=>'1088','municipio'=>'PRADER' ,'id_dpto'=>'30'],
            ['id'=>'1089','municipio'=>'RESTREP' ,'id_dpto'=>'30'],
            ['id'=>'1090','municipio'=>'RIO FRÍ' ,'id_dpto'=>'30'],
            ['id'=>'1091','municipio'=>'ROLDANILL' ,'id_dpto'=>'30'],
            ['id'=>'1092','municipio'=>'SAN PEDR' ,'id_dpto'=>'30'],
            ['id'=>'1093','municipio'=>'SEVILL' ,'id_dpto'=>'30'],
            ['id'=>'1094','municipio'=>'TOR' ,'id_dpto'=>'30'],
            ['id'=>'1095','municipio'=>'TRUJILL' ,'id_dpto'=>'30'],
            ['id'=>'1096','municipio'=>'TULÚ' ,'id_dpto'=>'30'],
            ['id'=>'1097','municipio'=>'ULLO' ,'id_dpto'=>'30'],
            ['id'=>'1098','municipio'=>'VERSALLE' ,'id_dpto'=>'30'],
            ['id'=>'1099','municipio'=>'VIJE' ,'id_dpto'=>'30'],
            ['id'=>'1100','municipio'=>'YOTOC' ,'id_dpto'=>'30'],
            ['id'=>'1101','municipio'=>'YUMB' ,'id_dpto'=>'30'],
            ['id'=>'1102','municipio'=>'ZARZA' ,'id_dpto'=>'30'],
            ['id'=>'1103','municipio'=>'CARUR' ,'id_dpto'=>'31'],
            ['id'=>'1104','municipio'=>'MIT' ,'id_dpto'=>'31'],
            ['id'=>'1105','municipio'=>'PACO' ,'id_dpto'=>'31'],
            ['id'=>'1106','municipio'=>'PAPUNAU' ,'id_dpto'=>'31'],
            ['id'=>'1107','municipio'=>'TARAIR' ,'id_dpto'=>'31'],
            ['id'=>'1108','municipio'=>'YAVARAT' ,'id_dpto'=>'31'],
            ['id'=>'1109','municipio'=>'CUMARIB' ,'id_dpto'=>'31'],
            ['id'=>'1110','municipio'=>'LA PRIMAVER' ,'id_dpto'=>'31'],
            ['id'=>'1111','municipio'=>'PUERTO CARREÑ' ,'id_dpto'=>'31'],
            ['id'=>'1112','municipio'=>'SANTA ROSALI' ,'id_dpto'=>'31']
        ]);
    }
}
